### PR TITLE
Misc misspellings

### PR DESCRIPTION
**Pull request by MaherJendoubi**
Fix issue #4638

### CODE REVIEW

**Comment by antoniovs1029** [comment]
Hi, @MaherJendoubi , it seems all the pipelines are failing.

I have just had a quick look at all of this, and now it isn't a build error (like in your previous PR), but actually some Tests related to Entry points are failing. I am not sure why would it be the case, since it seems to me you only renamed `LastOccurenceWins `in the `ArgumentType ` enum and some comments.

I will rerun the tests on azure pipelines to see if there's any difference. And perhaps I will try to have a closer look later today. But in the meantime, it would also be great if you can investigate why the errors are occurring. Thanks for your collaboration!

**Comment by antoniovs1029** [comment]
Hi @MaherJendoubi . It seems that the problem is that you also need to update these files fixing there the misspellings:

https://github.com/dotnet/machinelearning/blob/master/test/BaselineOutput/Common/EntryPoints/core_ep-list.tsv

https://github.com/dotnet/machinelearning/blob/master/test/BaselineOutput/Common/EntryPoints/core_manifest.json

If you fix them in those files, the pipelines should run correctly now.

Those files can be thought as containing the description of the different components that ML.NET exposes as entry points. In the `Microsoft.ML.RunTests.TestEntryPoints.EntryPointCatalog` test (which was the test where your PR was failing), a new updated temporal version of those files is created and compared to those files, if they are not the same, the test failed. This new temporal version was affected by some of your changes... for example, your update to the [GamTrainer Summary](https://github.com/MaherJendoubi/machinelearning/blob/c38d81d70b27e46001431e700d5d4a0472d61617/src/Microsoft.ML.FastTree/GamTrainer.cs#L126). The summary of the trainers is also included in those files, so when updating the summary in the code, those other files should also be updated.

So, in general, I think that fixing the misspellings in the 2 files I've linked to above should be enough ;)

**Comment by MaherJendoubi** [comment]
Hi @antoniovs1029 Thanks a lot for the investigation! I fixed them but I still have 3 failing tests locally:

- [ ] [xUnit.net 00:00:03.62]     Microsoft.ML.InternalCodeAnalyzer.Tests.BestFriendTest.BestFriend [FAIL]
[xUnit.net 00:00:03.63]     Microsoft.ML.InternalCodeAnalyzer.Tests.ContractsCheckTest.ContractsCheckFix [FAIL]
  X Microsoft.ML.InternalCodeAnalyzer.Tests.BestFriendTest.BestFriend [1s 992ms]
  Error Message:
   Context: Diagnostics of test state
Expected diagnostic message to be "'D.D(float)' is inaccessible due to its protection level" was "'D.D(float)' est inaccessible en raison de son niveau de protection"

Diagnostic:
    // Test0.cs(23,21): error CS0122: 'D.D(float)' est inaccessible en raison de son niveau de protection

- [ ] Expected: True
Actual:   False
  Stack Trace:
     at Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier.Equal[T](T expected, T actual, String message) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Testing.Verifiers.XUnit/XUnitVerifier.cs:line 47
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticResults(IEnumerable`1 actualResults, ImmutableArray`1 analyzers, DiagnosticResult[] expectedResults, IVerifier verifier) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 267
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticsAsync(ValueTuple`2[] sources, ValueTuple`2[] additionalFiles, MetadataReference[] additionalMetadataReferences, DiagnosticResult[] expected, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 151
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.RunAsync(CancellationToken cancellationToken) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 182
   at Microsoft.ML.InternalCodeAnalyzer.Tests.BestFriendTest.BestFriend() in C:\Users\M_Jendoubi\Documents\GitHub\machinelearning\test\Microsoft.ML.CodeAnalyzer.Tests\Code\BestFriendTest.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
  X Microsoft.ML.InternalCodeAnalyzer.Tests.ContractsCheckTest.ContractsCheckFix [2s 18ms]
  Error Message:
   Context: Diagnostics of test state
Expected diagnostic message to be "'ICancelable' is inaccessible due to its protection level" was "'ICancelable' est inaccessible en raison de son niveau de protection"

Diagnostic:
    // Test1.cs(752,24): error CS0122: 'ICancelable' est inaccessible en raison de son niveau de protection

- [ ] Expected: True
Actual:   False
  Stack Trace:
     at Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier.Equal[T](T expected, T actual, String message) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Testing.Verifiers.XUnit/XUnitVerifier.cs:line 47
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticResults(IEnumerable`1 actualResults, ImmutableArray`1 analyzers, DiagnosticResult[] expectedResults, IVerifier verifier) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 267
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticsAsync(ValueTuple`2[] sources, ValueTuple`2[] additionalFiles, MetadataReference[] additionalMetadataReferences, DiagnosticResult[] expected, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 151
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.RunAsync(CancellationToken cancellationToken) in /_/src/Tools/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 182
   at Microsoft.ML.InternalCodeAnalyzer.Tests.ContractsCheckTest.ContractsCheckFix() in C:\Users\M_Jendoubi\Documents\GitHub\machinelearning\test\Microsoft.ML.CodeAnalyzer.Tests\Code\ContractsCheckTest.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:03.74]     Microsoft.ML.InternalCodeAnalyzer.Tests.ContractsCheckTest.ContractsCheck [FAIL]
  X Microsoft.ML.InternalCodeAnalyzer.Tests.ContractsCheckTest.ContractsCheck [132ms]
  Error Message:
   Context: Diagnostics of test state
Expected diagnostic message to be "Inconsistent accessibility: parameter type 'IHostEnvironment' is less accessible than method 'TypeName.TypeName(IHostEnvironment, float, int)'" was "Accessibilité incohérente : le type de paramètre 'IHostEnvironment' est moins accessible que la méthode 'TypeName.TypeName(IHostEnvironment, float, int)'"

Diagnostic:
    // Test0.cs(15,16): error CS0051: Accessibilité incohérente : le type de paramètre 'IHostEnvironment' est moins accessible que la méthode 'TypeName.TypeName(IHostEnvironment, float, int)'

**Comment by antoniovs1029** [comment]
Hi, @MaherJendoubi and thanks for your contributions!

I don't know why are your tests failing in your local machine, since all of the tests have already passed on the CI pipelines:
https://github.com/dotnet/machinelearning/pull/4642/checks

I've also ran the tests of your fork, locally in my Visual Studio, and they also pass without any problem.

Since all the tests have passed there, I will merge this PR :D Thanks again.

**Comment by MaherJendoubi** [comment]
Hi @antoniovs1029,
You could easily reproduce my local errors by spinning up an Azure VM Windows 10 French OS.

**Pull request merged**
