### PR TITLE
File-scoped namespaces in files under `Utilities` (`Microsoft.ML.Core`)

### PR DESCRIPTION
**Pull request by Lehonti**

### CODE REVIEW

**Comment by michaelgsharp** [comment]
@Lehonti this one is failing with this error.
```
warning MSML_ContractsExceptAsExpression: Something should be done with the exception created by 'ExceptParam'
```
I haven't been able to pinpoint where in the code this is coming from since there are lots of files to go through, but it looks like something may have been slightly changed besides just the file-scoped namespace.

**Comment by michaelgsharp** [comment]
Would you be able to take a look and figure out what exactly is different?

**Comment by Lehonti** [comment]
Hello @michaelgsharp , I am not sure what may be causing this. I just checked and tried to find if anything was different, but there wasn't anything. In fact, I went as far as re-doing the changes (I took the files that are currently in `main` and applied the file-scoped namespace action again), but the resulting files are identical, bit by bit, so there were no changes that I could commit.

I am not sure if I can show you that the only changes are, indeed, the file-scoped namespaces; but if we want to be more practical, we could close this pull request and I would encourage you at Microsoft to do this task (given that reviewing the changes is a lot more work than running the relevant refactoring commands in Visual Studio).

**Pull request closed without merging**
