### PR TITLE
Use dotnet certificate

### PR DESCRIPTION
**Pull request by mmitche**
https://github.com/dotnet/announcements/issues/184

### CODE REVIEW

**Comment by mmitche** [comment]
Official test https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4751885&view=results

**Comment by mmitche** [comment]
I think there is an issue with the msbuild version in use. It may not support the metadata update as expected.

**Comment by mmitche** [comment]
Updated to the 400 band SDK: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4752233&view=results

**Review by michaelgsharp — APPROVED** [review]
I fixed the conflict and it looks good. I'll merge when the tests finish.

**Pull request merged**
