### PR TITLE
Contributing: Fix typos

### PR DESCRIPTION
**Pull request by MaherJendoubi**
Fixing some typos

### CODE REVIEW

**Comment by antoniovs1029** [comment]
Changing the name of the variable only in the places you did seems to not be enough, since [all of the builds are failing](https://dev.azure.com/dnceng/public/_build/results?buildId=474936&view=results) with this error:

`Experiment/SuggestedPipelineRunDetails/SuggestedPipelineRunDetail.cs(26,163): error CS1061: 'PipelineScore' does not contain a definition for 'RunSucceded' and no accessible extension method 'RunSucceded' accepting a first argument of type 'PipelineScore' could be found (are you missing a using directive or an assembly reference?) `

@MaherJendoubi did you try to build this in your machine before opening the PR? I would think that this would have to fail on your machine too. Please, try to fix this renaming and check if it build in your machine before updating this PR. Thanks!

**Comment by MaherJendoubi** [comment]
@antoniovs1029 My mistake. I am working on fixing it.

**Comment by justinormont** [comment]
I think you're missing the one here:
https://github.com/dotnet/machinelearning/blob/54b2b041da42b18f947b5833e64c9763108c7d32/src/Microsoft.ML.AutoML/Experiment/Experiment.cs#L96-L100

**Comment by MaherJendoubi** [comment]
@justinormont actually, I have issues to compile the whole solution. But, I fixed the missing changes.

**Comment by antoniovs1029** [comment]
> @justinormont actually, I have issues to compile the whole solution. But, I fixed the missing changes.

@MaherJendoubi . Unfortunately the builds are still failing, as you can see here:

The error is

`Experiment/SuggestedPipelineRunDetails/SuggestedPipelineRunDetail.cs(26,163): error CS1061: 'PipelineScore' does not contain a definition for 'RunSucceded' and no accessible extension method 'RunSucceded' accepting a first argument of type 'PipelineScore' could be found (are you missing a using directive or an assembly reference?)
`

So there are still places where variables need to be renamed.

Can you tell us what problem are you encountering when building ML.NET? I might be able to assist you so you can run things locally and make it easier for you to fix this problem. Thanks for your contributions!

**Comment by justinormont** [comment]
You can also check on the errors in the CI tests. You can see a build error here:
https://dev.azure.com/dnceng/public/_build/results?buildId=475367&view=logs&j=ac97a0ee-ee90-5a55-af17-a5a589fa545f&t=fdd5b9c0-ee9c-5c91-333c-dcdd6c90934e&l=251


Which ends with:

```
/1/s/dir.traversal.targets(25,5): error : Build failed. See earlier errors. [/__w/1/s/build.proj]

Build FAILED.

EXEC : CMake warning :  [/__w/1/s/src/Native/build.proj]
Experiment/SuggestedPipelineRunDetails/SuggestedPipelineRunDetail.cs(26,163): error CS1061: 'PipelineScore' does not contain a definition for 'RunSucceded' and no accessible extension method 'RunSucceded' accepting a first argument of type 'PipelineScore' could be found (are you missing a using directive or an assembly reference?) [/__w/1/s/src/Microsoft.ML.AutoML/Microsoft.ML.AutoML.csproj]
/__w/1/s/dir.traversal.targets(25,5): error : Build failed. See earlier errors. [/__w/1/s/build.proj]
    1 Warning(s)
    2 Error(s)

Time Elapsed 00:06:
``` 

This error is pointing to this line:
https://github.com/MaherJendoubi/machinelearning/blob/1374699c73d374bacd6500f9db07b35d20ac62f7/src/Microsoft.ML.AutoML/Experiment/SuggestedPipelineRunDetails/SuggestedPipelineRunDetail.cs#L26

Renaming within Visual Studio is easier as it generally finds all occurrences when renaming.

---

You can navigate to the build output by clicking on the warning/errors on Checks page (or by clicking the Details for the CI on this page):
> image

**Comment by MaherJendoubi** [comment]
@antoniovs1029 @justinormont I still have one error : 
image

**Comment by justinormont** [comment]
@MaherJendoubi: I can build your branch, and the unit tests pass (on macOS). I'm just going to retry the CI checks; they seem rather unstable currently.

**Comment by MaherJendoubi** [comment]
@antoniovs1029 Thank you for your feedback. Build and Run are successful for me using commandline but still having issues when building using VS2019 Preview Version 16.5.0 Preview 1.

**Pull request merged**
