### PR TITLE
Add targeting .Net 8.0 for DataFrame package

### LINKED ISSUE #7167: Add targeting .Net 8.0 for DataFrame package
1. Add targeting .Net 8.0 for DataFrame package
2. Update dependency to Apache.Arrow to use newer version
3.  Fix code that use Apache.Arrow obsolete methods

### PR DESCRIPTION
**Pull request by asmirnov82**
Fixes #7167

### CODE REVIEW

**Comment by asmirnov82** [comment]
TestTokenizerUsingExternalVocab test fails, because external vocabulary is not available by https://pythia.blob.core.windows.net/public/encoding/gpt2.tiktoken url

**Comment by JakeRadMSFT** [comment]
azp /run

**Review by JakeRadMSFT — APPROVED** [review]

**Pull request merged**
