### PR TITLE
update wikipedia detox line 83 - Add missing quote

### PR DESCRIPTION
**Pull request by JonathanLoscalzo**
Fixes a missing quote.
It solves this warning 
image

when you train your model from [sentiment-analysis example](https://docs.microsoft.com/es-es/dotnet/machine-learning/tutorials/sentiment-analysis)

### CODE REVIEW

**Comment by justinormont** [comment]
Another method of fixing this is to modify the loader function disable parsing of quotes instead. This assumes there are no extraneous tabs within the file, which I believe is correct. This would involve adding the parameter `AllowQuoting=true` in the [example's line](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis): `pipeline.Add(new TextLoader(_dataPath).CreateFrom<SentimentData>());`. At the same time, `AllowSparse=false` should be set in the example as no sparse data exists in the dataset.

It's a reasonable question to pose, of how much should the user need to clean-up a dataset before use? Should the loader function be better at handling situations like this? TSV/CSV isn't standardized, and If we improve our TSV/CSV parsing to handle common encodings/escapings, which ones would we support?

**Comment by JonathanLoscalzo** [comment]
@justinormont 
I change this line in [this example](https://docs.microsoft.com/es-es/dotnet/machine-learning/tutorials/sentiment-analysis)

``
pipeline.Add(new TextLoader(_dataPath).CreateFrom<SentimentData>(allowQuotedStrings: false));
``

and the warning seems to have been resolved, without adding the missing quote

but: 

with"allowQuotedStrings" **true** (default)
``
Accuracy: 61,11 %
Auc: 85,19 %
F1Score: 72,00 %
``

and with "allowQuotedStrings" **false** (new test)
``
Accuracy: 66,67 %
Auc: 84,57 %
F1Score: 75,00 %
``

I don't know if that is a behavior expected. 
I'm new in ML, and I started playing with ML.Net.

> Should the loader function be better at handling situations like this?

I think it could have a transforming function as a parameter for special cases, or just for "hook per line readed". 

>  which ones should we support?

This data is a possibility in real world. Data "malformed", while the loader discarts this data, it's ok for me.
But it's true that, maybe, we would read information from a log store in production, and we try to detect some defects or anomalies.
Could "reader/loader" solve the formatting problem?

**Comment by TomFinley** [comment]
Hi @JonathanLoscalzo and @justinormont -- I belive @justinormont 's original proposed suggestion of changing the text loader settings so they correctly change the file is probably the best, since changing data is a fairly invasive operation -- sometimes it is regrettably necessary since after all we could hardly expect the text loader to read every conceivable format of file, but in this case I think it can be made to work with the simple changes to the settings @justinormont suggests.

**Comment by JonathanLoscalzo** [comment]
Hi @TomFinley @justinormont !
then it would be fine  to close this pull request and modify the tutorial documentation.
I don't know [ where is it ... ](https://docs.microsoft.com/es-es/dotnet/machine-learning/tutorials/sentiment-analysis).

Thanks for your time!

**Comment by justinormont** [comment]
Closed by request. 

@JonathanLoscalzo : Do you want to open another issue requesting the to add the parameters `AllowQuoting=true` & `AllowSparse=false` in the [example's line](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis): `pipeline.Add(new TextLoader(_dataPath).CreateFrom<SentimentData>());`?

**Pull request closed without merging**
