### PR TITLE
Update editor config and format samples

### PR DESCRIPTION
**Pull request by jwood803**
Update the `editorconfig` file to match the one in the [Roslyn repository](https://github.com/dotnet/roslyn/blob/main/.editorconfig).

Ran [dotnet-format](https://github.com/dotnet/format) on the samples projects

Updates #302 

cc// @michaelgsharp

### CODE REVIEW

**Comment by michaelgsharp** [comment]
I think the ubuntu failures are just transient failures we see with system.drawing on unix sometimes so I have kicked them off again. 

Taking a look at the rest. Thanks for submitting this.

**Comment by michaelgsharp** [comment]
@jwood803 sorry, I have been out of town for a bit. Back now.

This looks really good to me. I don't see any changes we don't want, and with the editor config hopefully we can keep it looking like this from now on. 

I can't approve this since its only a draft PR though. Is there a reason its not a full PR yet?

**Comment by jwood803** [comment]
@michaelgsharp No worries! I marked it ready for review. I just kept it as a draft for discussion 😄 

Should I go ahead and do more PRs for the other projects?

**Review by michaelgsharp — APPROVED** [review]
LGTM :shipit:

**Comment by michaelgsharp** [comment]
Yeah, I think we are good to move onto other projects now.

**Pull request merged**
