### PR TITLE
Added tests to check for cases of invalid LDist

### PR DESCRIPTION
**Pull request by shaliniiit**
We are excited to review your PR.

So we can do the best job, please check:

- [x] There's a descriptive title that will make sense to other developers some time from now. 
- [x] There's associated issues. All PR's should have issue(s) associated - unless a trivial self-evident change such as fixing a typo. You can use the format `Fixes #nnnn` in your description to cause GitHub to automatically close the issue(s) when your PR is merged.
- [x] Your change description explains what the change does, why you chose your approach, and anything else that reviewers should know.
- [x] You have included any necessary tests in the same PR.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5929) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5929) before we can accept your contribution.<br/><br/>:x: shaliniiit [sign now](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5929)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/machinelearning?pullRequest=5929) it.</sub>

**Comment by michaelgsharp** [comment]
@shaliniiit this looks good. Are you able to sign the CLA so we can get it in?

**Comment by michaelgsharp** [comment]
@shaliniiit closing since the CLA still hasn't been signed so we can't merge it in. If you are able to sign it we can re-open the PR to merge it.

**Comment by shaliniiit** [comment]
Hi,
Just signed the CLA. Please feel free to check it in.

**Comment by michaelgsharp** [comment]
Re-opening as the CLA has now been signed. Thanks @shaliniiit!

**Review by michaelgsharp — APPROVED** [review]
:shipit: LGTM. Thanks for your contribution!

**Pull request merged**
