### PR TITLE
Enhance code coverage bot message.

### PR DESCRIPTION
**Pull request by codemzs**

### CODE REVIEW

**Comment by codemzs** [comment]
@sharwell Thanks for your input. Some of us actually like this format, I will take a vote on this and decide.

CC: @ViktorHofer

**Comment by justinormont** [comment]
Would it be possible to put the extra info in a collapsible box?

<details><summary>CLICK ME</summary>
<p>

| [Impacted Files](https://codecov.io/gh/dotnet/machinelearning/pull/2235?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [...soft.ML.TestFramework/DataPipe/TestDataPipeBase.cs](https://codecov.io/gh/dotnet/machinelearning/pull/2235/diff?src=pr&el=tree#diff-dGVzdC9NaWNyb3NvZnQuTUwuVGVzdEZyYW1ld29yay9EYXRhUGlwZS9UZXN0RGF0YVBpcGVCYXNlLmNz) | `70.05% <0%> (-0.33%)` | :arrow_down: |
| [...soft.ML.Data/DataLoadSave/Text/TextLoaderCursor.cs](https://codecov.io/gh/dotnet/machinelearning/pull/2235/diff?src=pr&el=tree#diff-c3JjL01pY3Jvc29mdC5NTC5EYXRhL0RhdGFMb2FkU2F2ZS9UZXh0L1RleHRMb2FkZXJDdXJzb3IuY3M=) | `82.86% <0%> (+0.2%)` | :arrow_up: |
| [...StandardLearners/Standard/LinearModelParameters.cs](https://codecov.io/gh/dotnet/machinelearning/pull/2235/diff?src=pr&el=tree#diff-c3JjL01pY3Jvc29mdC5NTC5TdGFuZGFyZExlYXJuZXJzL1N0YW5kYXJkL0xpbmVhck1vZGVsUGFyYW1ldGVycy5jcw==) | `60.9% <0%> (+0.26%)` | :arrow_up: |
| [src/Microsoft.ML.Maml/MAML.cs](https://codecov.io/gh/dotnet/machinelearning/pull/2235/diff?src=pr&el=tree#diff-c3JjL01pY3Jvc29mdC5NTC5NYW1sL01BTUwuY3M=) | `26.21% <0%> (+1.45%)` | :arrow_up: |

</p>
</details>

<br>
via: https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f

**Comment by sharwell** [comment]
@justinormont It is not currently possible. I requested that behavior from codecov a long time back and will send them a reminder.

**Comment by TomFinley** [comment]
Am I the only one that can't see any information out of codecov at all? I have a spinning webpage that's been "loading" for minutes.

Unrelated: it *seems* like the codecov build is actually blocking the gate? The entire purpose of adding it as a separate build was so it would not do that.

**Comment by codemzs** [comment]
@TomFinley link to the PR please? CodeCoverge-CI should not block the merge since it’s not the required step?

**Comment by codemzs** [comment]
@TomFinley Below is the snapshot of the scenario where main CI has finished but code coverage CI has not and you can still merge:

image

**Comment by codemzs** [comment]
@sharwell The PR view isn't working so it will be good to have a snapshot of what files are affected even though it won't show the whole list but it will list the top files.

**Pull request merged**
