### PR TITLE
Update to Microsoft.CodeAnalysis 3.3.1

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by eerhardt** [comment]
Tagging @JakeRadMSFT, since this affects Microsoft.ML.CodeGenerator, which is used by the CLI and VS Model Builder.

**Comment by sharwell** [comment]
@eerhardt I only intended to make the change for the code analyzers. I'm happy to restrict it if you aren't ready to update the code generator.

**Comment by sharwell** [comment]
@eerhardt this pull request no longer alters the code generator dependencies

**Comment by sharwell** [comment]
@harishsk for review

**Pull request merged**
