### PR TITLE
fix #5767 issue with DataFrame Merge method

### LINKED ISSUE #5767: DataFrame merge method change Left and Right values
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 5.0.201

### Issue

- **What did you do?**

I used DataFrame,Merge method with Algo Inner and Right dataframe having less rows than left dataframe

- **What happened?**

Right values are merged into Left columns and Left values into right columns

- **What did you expect?**

I expected the left values to be merged into columns "_left" suffix and right values into columns with "_right" suffix

### Source code / logs

Unit test to reproduce (expect to work same way for (1,2) and (2,1)):

[Theory]
        [InlineData(1, 2)]
        [InlineData(2, 1)]
        public void TestMerge_3(int leftCount, int rightCount)
        {
            DataFrame left = MakeDataFrameWithNumericColumns(leftCount, false);
            DataFrameColumn leftStringColumn = new StringDataFrameColumn("String", Enumerable.Range(0, leftCount).Select(x => "Left"));
            left.Columns.Insert(left.Columns.Count, leftStringColumn);

            DataFrame right = MakeDataFrameWithNumericColumns(rightCount, false);
            DataFrameColumn rightStringColumn = new StringDataFrameColumn("String", Enumerable.Range(0, rightCount).Select(x => "Right"));
            right.Columns.Insert(right.Columns.Count, rightStringColumn);

            DataFrame merge = left.Merge<int>(right, "Int", "Int", joinAlgorithm: JoinAlgorithm.Inner);

            Assert.Equal("Left", (string)merge.Columns["String_left"][0]);
            Assert.Equal("Right", (string)merge.Columns["String_right"][0]);
        }

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

### PR DESCRIPTION
**Pull request by asmirnov82**
Fixes #5767

Fix issue related to DataFrame Merge method with Algorithm.Inner, in case when right dataframe has more rows. that left

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5768) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5768) before we can accept your contribution.<br/><br/>:x: asmirnov82 [sign now](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5768)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/machinelearning?pullRequest=5768) it.</sub>

**Review by pgovind — APPROVED** [review]
Yup, this LGTM!

**Comment by pgovind** [comment]
Thank you for the PR @asmirnov82 ! Really appreciate the work here!

**Comment by asmirnov82** [comment]
You are welcome @pgovind. Do I need to click "Close PR" to merge it or you will merge it by yourself?

**Comment by pgovind** [comment]
> Do I need to click "Close PR" to merge it or you will merge it by yourself?

I'll do it :) We're working on fixing the CI in this repo though, so this will have to wait until CI turns green

**Comment by asmirnov82** [comment]
Thanks!

**Comment by pgovind** [comment]
@asmirnov82, I believe CI is fixed in the repo now. Can you rebase your PR on the latest dotnet/main?

**Pull request merged**
