### PR TITLE
Updated arcade to the latest version

### PR DESCRIPTION
**Pull request by michaelgsharp**
Since we don't have it set up to automatically update arcade yet, this PR manually updates arcade to the latest version.

### CODE REVIEW

**Comment by ericstj** [comment]
>MSBUILD : error MSB1021: Cannot create an instance of the logger. The given assembly name or codebase was invalid. (0x80131047)
Switch: /home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.arcade.sdk/6.0.0-beta.21253.2/tools/netcoreapp2.1/Microsoft.DotNet.Arcade.Sdk.dll

If I look at that package it doesn't have this path: `tools/netcoreapp2.1`  I think you need to update something to `tools/netcoreapp3.1`.  Perhaps in our own yml somewhere?

**Comment by ericstj** [comment]
Here it is: https://github.com/dotnet/machinelearning/blob/04dda55ab0902982b16309c8e151f13a53e9366d/eng/common/tools.sh#L312

**Comment by ericstj** [comment]
Looks like you're missing all changes that should have been applied in eng/common.  Darc update should copy those files to make them same version as arcade version you're picking up.

**Comment by ericstj** [comment]
Took a look at the failing code-coverage run.  It seems like it timed out while running tests.  

It seems to be Microsoft.ML.Tests like we were seeing before:
https://dev.azure.com/dnceng/public/_build/results?buildId=1138394&view=logs&j=12b34f85-96db-5b04-05cf-faf2be278867&t=557f61c0-297e-5c2f-1c50-9536da345a61

However I don't see an obvious hanging test:
https://dev.azure.com/dnceng/_apis/resources/Containers/7060027/Windows_x64%20D?itemPath=Windows_x64%20D%2Fartifacts%2Flog%2FDebug%2FMicrosoft.ML.Tests_netcoreapp2.1_x64.log

**Comment by michaelgsharp** [comment]
@ericstj so just a retrigger of the code coverage build had it pass this time. Its just so close to the limit that anything taking extra time can cause it to time out. We should take a look at it at some point and see if we can make it more stable. But everything has passed for now.

**Comment by ericstj** [comment]
If it's hovering close to the limit and we don't think there's a problem there we could always relax that limit.  For now we can just 👀

**Review by ericstj — APPROVED** [review]

**Pull request merged**
