### PR TITLE
Fix dependencies that are flagging CG

### PR DESCRIPTION
**Pull request by ericstj**

### CODE REVIEW

**Comment by ericstj** [comment]
We need Google.Protobuf mirrored to the internal nuget feed.

**Comment by tarekgh** [comment]
Seeing some errors which I assume not related to the change as I saw similar failure on runtime repo. 

```
D:\a\1\s\test\Microsoft.ML.Tests\Microsoft.ML.Tests.csproj : error NU1603: Microsoft.ML.OnnxConverter depends on Google.Protobuf (>= 3.19.6) but Google.Protobuf 3.19.6 was not found. An approximate best match of Google.Protobuf 3.20.0 was resolved. [D:\a\1\s\Microsoft.ML.sln]
D:\a\1\s\test\Microsoft.ML.Tests\Microsoft.ML.Tests.csproj : error NU1603: Microsoft.ML.OnnxTransformer depends on Google.Protobuf (>= 3.19.6) but Google.Protobuf 3.19.6 was not found. An approximate best match of Google.Protobuf 3.20.0 was resolved. [D:\a\1\s\Microsoft.ML.sln]
D:\a\1\s\test\Microsoft.ML.Tests\Microsoft.ML.Tests.csproj : error NU1603: Microsoft.ML.TensorFlow depends on Google.Protobuf (>= 3.19.6) but Google.Protobuf 3.19.6 was not found. An approximate best match of Google.Protobuf 3.20.0 was resolved. [D:\a\1\s\Microsoft.ML.sln]
D:\a\1\s\test\Microsoft.ML.OnnxTransformerTest\Microsoft.ML.OnnxTransformerTest.csproj : error NU1603: Microsoft.ML.OnnxTransformer depends on Google.Protobuf (>= 3.19.6) but Google.Protobuf 3.19.6 was not found. An approximate best match of Google.Protobuf 3.20.0 was resolved. [D:\a\1\s\Microsoft.ML.sln]
D:\a\1\s\test\Microsoft.ML.IntegrationTests\Microsoft.ML.IntegrationTests.csproj : error NU1603: Microsoft.ML.OnnxConverter depends on Google.Protobuf (>= 3.19.6) but Google.Protobuf 3.19.6 was not found. An approximate best match of Google.Protobuf 3.20.0 was resolved. [D:\a\1\s\Microsoft.ML.sln]
D:\a\1\s\test\Microsoft.ML.IntegrationTests\Microsoft.ML.IntegrationTests.csproj : error NU1603: Microsoft.ML.OnnxTransformer depends on Google.Protobuf (>= 3.19.6) but Google.Protobuf 3.19.6 was not found. An approximate best match of Google.Protobuf 3.20.0 was resolved. [D:\a\1\s\Microsoft.ML.sln]
D:\a\1\s\test\Microsoft.ML.PerformanceTests\Microsoft.ML.PerformanceTests.csproj : error NU1603: Microsoft.ML.TensorFlow depends on Google.Protobuf (>= 3.19.6) but Google.Protobuf 3.19.6 was not found. An approximate best match of Google.Protobuf 3.20.0 was resolved. [D:\a\1\s\Microsoft.ML.sln]
```

**Review by tarekgh — APPROVED** [review]

**Comment by ericstj** [comment]
> Google.Protobuf 3.19.6 was not found

Those errors are all due to the package not being mirrored.  I had the eng team fix that and the rerun should resolve it.

**Comment by ericstj** [comment]
The one failure we have here is this:
```
Unhandled exception: System.AggregateException: One or more errors occurred. (The CancellationTokenSource has been disposed.)
 ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at Microsoft.ML.AutoML.AutoMLExperiment.<>c__DisplayClass26_1.<RunAsync>g__handler|4(Object o, EventArgs e) in /__w/1/s/src/Microsoft.ML.AutoML/AutoMLExperiment/AutoMLExperiment.cs:line 270
   at Microsoft.ML.AutoML.AggregateTrainingStopManager.<.ctor>b__4_0(Object o, EventArgs e) in /__w/1/s/src/Microsoft.ML.AutoML/AutoMLExperiment/IStopTrainingManager.cs:line 129
   at Microsoft.ML.AutoML.TimeoutTrainingStopManager.<.ctor>b__5_0(Object o, EventArgs e) in /__w/1/s/src/Microsoft.ML.AutoML/AutoMLExperiment/IStopTrainingManager.cs:line 72
   at Microsoft.ML.AutoML.CancellationTokenStopTrainingManager.<.ctor>b__5_0() in /__w/1/s/src/Microsoft.ML.AutoML/AutoMLExperiment/IStopTrainingManager.cs:line 38
   at System.Threading.CancellationToken.<>c.<Register>b__12_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.TimerCallback(Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Unhandled exception. System.AggregateException: One or more errors occurred. (The CancellationTokenSource has been disposed.)
 ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at Microsoft.ML.AutoML.AutoMLExperiment.<>c__DisplayClass26_1.<RunAsync>g__handler|4(Object o, EventArgs e) in /__w/1/s/src/Microsoft.ML.AutoML/AutoMLExperiment/AutoMLExperiment.cs:line 270
   at Microsoft.ML.AutoML.AggregateTrainingStopManager.<.ctor>b__4_0(Object o, EventArgs e) in /__w/1/s/src/Microsoft.ML.AutoML/AutoMLExperiment/IStopTrainingManager.cs:line 129
   at Microsoft.ML.AutoML.TimeoutTrainingStopManager.<.ctor>b__5_0(Object o, EventArgs e) in /__w/1/s/src/Microsoft.ML.AutoML/AutoMLExperiment/IStopTrainingManager.cs:line 72
   at Microsoft.ML.AutoML.CancellationTokenStopTrainingManager.<.ctor>b__5_0() in /__w/1/s/src/Microsoft.ML.AutoML/AutoMLExperiment/IStopTrainingManager.cs:line 38
   at System.Threading.CancellationToken.<>c.<Register>b__12_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.TimerCallback(Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Aborted (core dumped)
```

@LittleLittleCloud I opened https://github.com/dotnet/machinelearning/issues/6416

**Pull request merged**
