### PR TITLE
Fixes Code Coverage in Arcade

### PR DESCRIPTION
**Pull request by Lynx1820**

### CODE REVIEW

**Comment by michaelgsharp** [comment]
The updated restore paths are missing from the yml file.

**Comment by antoniovs1029** [comment]
The AutoFitMaxExperimentTimeTest failed on one MacOS config, saying it can't load the SymSgdNative library. I've seen that error once on another run of MacOS on another pipeline. Maybe we should consider modifying the test to exclude any trainer that uses SymSgdNative... I think it's StochasticDualCoordinateAscent trainer only (or was it OnlineGradientDescent?)

To remove one trainer from an experiment, use this:
https://github.com/dotnet/machinelearning/blob/c2f8ed5c9c478194fa6c7e387bc9f8fc43e4e0bc/test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs#L132-L133

Here's the enum of possible trainers:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.automl.regressiontrainer?view=ml-dotnet-preview

**Comment by michaelgsharp** [comment]
Everything looks good to me. I'll approve it as soon as the code coverage test finishes.

**Comment by Lynx1820** [comment]
> The AutoFitMaxExperimentTimeTest failed on one MacOS config, saying it can't load the SymSgdNative library. I've seen that error once on another run of MacOS on another pipeline. Maybe we should consider modifying the test to exclude any trainer that uses SymSgdNative... I think it's StochasticDualCoordinateAscent trainer only (or was it OnlineGradientDescent?)
> 
> To remove one trainer from an experiment, use this:
> https://github.com/dotnet/machinelearning/blob/c2f8ed5c9c478194fa6c7e387bc9f8fc43e4e0bc/test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs#L132-L133
> 
> Here's the enum of possible trainers:
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.automl.regressiontrainer?view=ml-dotnet-preview

It seems like this is a random failure. I will investigate more before excluding the trainer.

**Comment by michaelgsharp** [comment]
Code coverage build timed out. I'll retry it. not sure why its so much slower.

**Review by michaelgsharp — APPROVED** [review]
LTGM

**Pull request merged**
