### PR TITLE
Fixed official builds for Arcade SDK

### PR DESCRIPTION
**Pull request by mstfbl**
This PR fixes the official builds for ML.NET's Arcade SDK changes. 

The failing trusted CI machine DDVSOWINAGE072 has been fixed, more info in this issue: https://github.com/dotnet/core-eng/issues/11513

Link to the trusted and successful build of these changes: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4255993&view=results

### CODE REVIEW

**Review by justinormont — APPROVED** [review]
Nothing particular to AutoML in this PR. So signing off on the AutoML portion so it can be merged once the bulk of the code is reviewed.

**Comment by antoniovs1029** [comment]
Currently there's a problem with the published nugets, where they require the 

I discussed this with @michaelgsharp and it seems it's simply fixed by using this:
```C#
    <PackageReference Include="MlNetMklDeps" Version="$(MlNetMklDepsPackageVersion)" >
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```

on the Mkl Components .csproj.

We tested it locally and it seemed to work, but it would be necessary to test it on the publishing pipeline to make sure about this.

**Comment by frank-dong-ms** [comment]
what is the problem with the published nugets?

---
In reply to: [735992170](https://github.com/dotnet/machinelearning/pull/5512#issuecomment-735992170) [](ancestors = 735992170)

**Comment by frank-dong-ms** [comment]
> scriptroot="$( cd -P "$( dirname "$source" )" && pwd )"

why we need these changes under eng/common folder? are they related to official build?

---
Refers to: eng/common/cibuild.sh:14 in 3fcf127. [](commit_id = 3fcf127692d5fccab3670178fb36828ef96f22f1, deletion_comment = True)

**Review by frank-dong-ms — APPROVED** [review]
:shipit:

**Comment by frank-dong-ms** [comment]
> scriptroot="$( cd -P "$( dirname "$source" )" && pwd )"

Looks like codeflow is not showing the change correctly, Mustafa is adding execute permission to all *.sh files and that looks good to me.

---
In reply to: [735998269](https://github.com/dotnet/machinelearning/pull/5512#issuecomment-735998269) [](ancestors = 735998269)

---
Refers to: eng/common/cibuild.sh:14 in 3fcf127. [](commit_id = 3fcf127692d5fccab3670178fb36828ef96f22f1, deletion_comment = True)

**Pull request merged**
