### PR TITLE
Fix wrong type conversion on PrimitiveDataFrameColumn

### LINKED ISSUE #6829: [DataFrame] Null Reference on ElementwiseEquals on DateTime columns from DataFrame
**System Information (please complete the following information):**
 - OS & Version: [e.g. Windows 10] Windows 10
 - ML.NET Version: [e.g. ML.NET v1.5.5] N/A
 - Microsoft.Data.Analysis Version: 0.20.1
 - .NET Version: [e.g. .NET 5.0]: 7.0.110

**Describe the bug**
Invoking ElementwiseEquals on a PrimitiveDataFrameColumn<DateTime> obtained by accessing DataFrame["ColumnName"] throws NullReferenceException

**To Reproduce**
1. Create a PrimitiveDataFrameColumn<DateTime> with some values
2. Create a dataframe with the column using its constructor
3. Access the dataframe's column by using the `this[string column]` getter, es: `df["ColumnName"]`
4. Call the ElementwiseEquals method on the column obtained through the DataFrame
5. Observe that a NullReferenceException is thrown.
6. Call the same method on the column passed to the DataFrame constructor.
7. Observe that no exceptions are thrown

**Expected behavior**
`df["Test"]` should behave like `column` and should not throw exceptions.

**Screenshots, Code, Sample Projects**
Reproduction example:
```
#r "nuget: Microsoft.Data.Analysis, 0.20.1"
using Microsoft.Data.Analysis;

var column = new DateTimeDataFrameColumn("Test");
column.Append(DateTime.Today);
var df = new DataFrame(column);
Console.WriteLine(column == df["Test"]); // true
Console.WriteLine(column.ElementwiseEquals(DateTime.Today).Any()); // True
df["Test"].ElementwiseEquals(DateTime.Today) // Throws NullReferenceException
```

**Stack trace**
Error: System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.ElementwiseEqualsImplementation[U](U value)
at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.ElementwiseEquals[U](U value)
at Submission#6.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

### PR DESCRIPTION
**Pull request by novelhawk**
Fixes #6829

Adds the patch commented by @asmirnov82 in #6831

Updated only the *.tt template, tried generating the *.cs through Visual Studio but it leaves blank lines where the templating is (the current files don't have it so I immagine there is a next step/I'm doing something wrong)

Also couldn't manage to run tests due to errors with arcade and formatting during compilation.

### CODE REVIEW

**Comment by novelhawk** [comment]
@dotnet-policy-service agree

**Comment by LittleLittleCloud** [comment]
Did you include the generated .cs file from .tt as well. Can't find it in this PR.

**Comment by novelhawk** [comment]
No I had problems generating them.. The generated files were full of blank lines that the ones in the repo don't have, what's the correct way to generate them?
Also couldn't run test due to formatting compilation errors but they seem to pass in CI

**Comment by asmirnov82** [comment]
@novelhawk, you can generate tt files using text transform utility in command line (https://learn.microsoft.com/en-us/visualstudio/modeling/generating-files-with-the-texttransform-utility) or just saving changed template in VS. I opened your branch and generated file on my laptop - it's fine, no extra spaces. I included it into PR to your repo:

https://github.com/novelhawk/machinelearning/pull/1

I also update you unit tests (currently it's running successfuly even on branch without actual fix). Fix is related to the issue of calling ElementwiseEquals with scalar DateTime parameter, so I change the test to use SampleData as paramer df["DateTime1"].ElementwiseEquals(SampleDateTime); only first element in the DateTime1 column is equal to it, so only equalsToScalarResult[0] should be True. 
You don't have to reopened this PR, it should be updated automaticaly after fix is merged to your repo.

**Comment by novelhawk** [comment]
I'm probably missing some dependencies or maybe I have an outdated version of the generator, running
`TextTransformCore --version` yields `17.6.36396+561222c835` and I have installed VS 2022 Community if this is investigated in the future.

Anyhow thanks for the help, I've merged your PR

**Review by asmirnov82 — APPROVED** [review]

**Review by LittleLittleCloud — APPROVED** [review]

**Pull request merged**
