### PR TITLE
Issue #104: Update the build tools to 2.1.200

### LINKED ISSUE #104: Update BuildTools to .NET Core 2.1.200
.NET Core 2.1 RC was released at //build with version `2.1.200`. We should probably shift to that.

### PR DESCRIPTION
**Pull request by markusweimer**
Issues:
  This closes #104

### CODE REVIEW

**Comment by eerhardt** [comment]
From a new person's perspective, this can be a bit confusing.  "BuildTools" is a non-shipping set of tools used by the .NET Core repos.  It is a set of extensions built on top of the .NET Core SDK that is a public shipping product.

The available versions of build tools can be seen here:

https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.DotNet.BuildTools

The version of the .NET Core SDK we are using is located in https://github.com/dotnet/machinelearning/blob/master/DotnetCLIVersion.txt.  (I know it is a bad name, but it is the same name that the rest of the .NET Core repos use...)

I think we can update both of these to the "latest".  .NET Core SDK => 2.1.200.  BuildTools => 2.2.0-preview1-02808-01

**Comment by markusweimer** [comment]
Oooh, now I get it. Please go ahead and make the changes, @eerhardt. I will hunt for something else as my 1st commit :)

**Comment by eerhardt** [comment]
You can totally do it, in order to get your "1st commit" badge.  You just need to change which file you are updating.

https://github.com/dotnet/machinelearning/blob/e1db5c53f0ff29fd97dca8087e7f7bedfd0b5124/DotnetCLIVersion.txt#L1

**Comment by TomFinley** [comment]
Just curious, does moving to .NET Core 2.1 give anything to us yet? I'm very excited about some things in it (`Span` in particular promises to simplify our lives a bunch, and I've spent perhaps more time than I should admit playing with `System.Runtime.Intrinsics`) but until its key new features are moved to .NET Standard, is there a reason to rush to adopt while it's still in RC?

**Comment by markusweimer** [comment]
@eerhardt, I have updated the other file :)

@TomFinley : We are already using .NET Core 2.1 SDK, but a preview instead of the release candidate. Not that IIRC, the SDK used is independent of the runtime target of the code. This PR doesn't change the target away from `netstandard20`.

**Comment by TomFinley** [comment]
Ah makes sense, thanks.

---
In reply to: [387902080](https://github.com/dotnet/machinelearning/pull/105#issuecomment-387902080) [](ancestors = 387902080)

**Comment by eerhardt** [comment]
I couple comments about the above, since this isn't stuff is hard to keep up with.

From the original issue:

>.NET Core 2.1 RC was released at //build with version 2.1.200.

The .NET Core Runtime and SDK have been versioning at different paces.  When 2.0 was released, both the runtime and SDK were v2.0 at the same time.  Their versions matched.  However, after the 2.0 runtime was released, there were new features added to the SDK that were more than just a patch version could take (new C# version, new MSBuild features, NuGet features, etc.).  At that time, it was decided to bump the SDK version to 2.1 in order to convey that there were more than just bug fixes in this release.  However, the runtime didn't release a new version at the same time.  So the 2.1 SDK still came with the 2.0 runtime.  People saw the huge issue this was going to be.  So we came up with a plan documented at https://github.com/dotnet/designs/pull/29/files.

The summary of the plan is that the SDK `2.1.300` and higher will ship with the `2.1` runtime.  Any SDK version between `2.1.0` - `2.1.299` still comes with the `2.0` runtime.  Going forward, the major/minor versions will match, as outlined in the design proposal.

> Just curious, does moving to .NET Core 2.1 give anything to us yet?

As stated above, with this change we still use the 2.0 runtime, and the latest released SDK.
This gives us a few minor advantages:
* It comes with the latest patched runtime (2.0.7)
* It gives new tooling features and bug fixes.  Latest compiler, msbuild, nuget, etc.

**Pull request merged**
