### PR TITLE
updating_files_with_LinearClassificationTrainer

### LINKED ISSUE #1069: SDCA (LinearClassificationTrainer) should be called SDCA in the codebase
For historic reasons, `SDCA` is named [`LinearClassificationTrainer`](https://github.com/dotnet/machinelearning/blob/044a6d3cf35a8076ecbbcca5cdb61b2f722f94e1/src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs#L1359) in the codebase.

SDCA (Stochastic Dual Coordinate Ascent), while quite good at many datasets, isn't the final answer for linear classification tasks as implied by the `LinearClassificationTrainer` moniker. For example, [`AveragedPerceptron`](https://github.com/dotnet/machinelearning/blob/b88d3460398c5b95745b476e40dd836f8f788cf6/src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs) tends to win on NLP tasks (ngrams and/or chargrams). 

Now is a great time to break with history and call SDCA, simply, `SDCA`.

### PR DESCRIPTION
**Pull request by utkarsh-42**
Fix #1069 
We are excited to review your PR.

So we can do the best job, please check:

- [ ] There's a descriptive title that will make sense to other developers some time from now. 
- [ ] There's associated issues. All PR's should have issue(s) associated - unless a trivial self-evident change such as fixing a typo. You can use the format `Fixes #nnnn` in your description to cause GitHub to automatically close the issue(s) when your PR is merged.
- [ ] Your change description explains what the change does, why you chose your approach, and anything else that reviewers should know.
- [ ] You have included any necessary tests in the same PR.

### CODE REVIEW

**Comment by Ivanidzo4ka** [comment]
>Conflicting files test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs

Can you resolve it?

**Comment by Ivanidzo4ka** [comment]
It's still fail at the build step
https://dnceng.visualstudio.com/public/_build/results?buildId=29759&view=logs

**Comment by Ivanidzo4ka** [comment]
@utkarsh-42  Do you plan to resolve conflicts? I'm intent to close this PR in few days if it remains abandon.

**Comment by artidoro** [comment]
I have to close this PR, because it has been inactive for too long. Please open a new PR if you solve the conflicts and are still interested in helping us solve the issue!

**Pull request closed without merging**
