### PR TITLE
Remove ISchema in ColumnBindingsBase

### PR DESCRIPTION
**Pull request by wschin**
This PR propose a naive way for removing `ISchema` in `ColumnBindingsBase`. It duplicates two utilities functions in the existing `ISchema`.

Duplicated functions:
```chsarp
        private Delegate GetMetadataGetterDelegate<TValue>(int col, string kind, Delegate del)
        {
            // REVIEW: We are facing a choice here: cache 'value' and get rid of 'schema' reference altogether,
            // or retain the reference but be more memory efficient. This code should not stick around for too long
            // anyway, so let's not sweat too much, and opt for the latter.
            ValueGetter<TValue> getter = (ref TValue value) => ((MetadataGetterDel<TValue>)del)(kind, col, ref value);
            return getter;
        }
```
```csharp
        private Schema MakeOutputSchema()
        {
            var builder = new SchemaBuilder();
            for (int i = 0; i < ColumnCount; ++i)
            {
                var meta = new MetadataBuilder();
                foreach (var kvp in GetMetadataTypes(i))
                {
                    var getter = Utils.MarshalInvoke(GetMetadataGetterDelegate<int>, kvp.Value.RawType, i, kvp.Key);
                    meta.Add(kvp.Key, kvp.Value, getter);
                }
                builder.AddColumn(GetColumnName(i), GetColumnType(i), meta.GetMetadata());
            }
            return builder.GetSchema();
       }
```

### CODE REVIEW

**Comment by TomFinley** [comment]
>         public bool TryGetColumnIndex(string name, out int col)

Hi @wschin! So you mentioned dissatisfaction with having to duplicate the conversion code. I suspect the root of this dissatisfaction is that you're continuing to use the `ISchema` interface methods (even though this thing no longer implements `ISchema`) to perform that translation -- otherwise there would be no code to duplicate, since there would be no common interface. So, let's consider this method, in particular. What purpose does it serve? As far as I can tell, none -- any call to it that would have been done in the past would be more effectively done by just referring to the output schema. So I feel like the bindings object should produce a schema object, but I don't think that the object itself should continue to behave like the output schema. If that's not what it is any more, then it shouldn't continue to act like it.

It's also unclear to me what the purpose of having this be a "lazy" object is. Whenever *anything* is done with this object, the first thing that is ever done, practically, is that the schema is inspected. So what is the purpose of making it `Lazy`?

---
Refers to: src/Microsoft.ML.Data/Transforms/ColumnBindingsBase.cs:519 in 5e5d342. [](commit_id = 5e5d3424e78824b67060f29fec5c349c86d1b14f, deletion_comment = False)

**Comment by wschin** [comment]
>         public bool TryGetColumnIndex(string name, out int col)

It probably means it's too early to remove ISchema here. I will first change the uses of old-fashion `TryGetColumnIndex` (and other `ISchema` members) to their equivalents defined in `ColumnBindingsBase.AsSchema`.
The reason of having `Lazy` is that the construction of `ColumnBindingsBase` usually relies on derived classes' attributes, which haven't been set yet after calling `ColumnBindingsBase`'s constructor.

---
In reply to: [446684574](https://github.com/dotnet/machinelearning/pull/1868#issuecomment-446684574) [](ancestors = 446684574)

---
Refers to: src/Microsoft.ML.Data/Transforms/ColumnBindingsBase.cs:519 in 5e5d342. [](commit_id = 5e5d3424e78824b67060f29fec5c349c86d1b14f, deletion_comment = False)

**Comment by TomFinley** [comment]
>         public bool TryGetColumnIndex(string name, out int col)

Yes, I expect you're probably right. It *may* be that we decide that `ISchema` does not need to go away, but becomes an internal interface to enable the construction of such objects that are in this kind of "liminal state" of being on the way to becoming `Schema`? Might this solve your dissatisfaction with code duplication, in a different way?

---
In reply to: [446755325](https://github.com/dotnet/machinelearning/pull/1868#issuecomment-446755325) [](ancestors = 446755325,446684574)

---
Refers to: src/Microsoft.ML.Data/Transforms/ColumnBindingsBase.cs:519 in 5e5d342. [](commit_id = 5e5d3424e78824b67060f29fec5c349c86d1b14f, deletion_comment = False)

**Comment by wschin** [comment]
>         public bool TryGetColumnIndex(string name, out int col)

Hello Tom, Pete told me that `ColumnBindingsBase` can be replaced with new `ColumnBindings`([https://github.com/dotnet/machinelearning/blob/342e13f8f32279493b3b3e0642a46b2e2690141c/src/Microsoft.ML.Data/Transforms/ColumnBindingsBase.cs#L647](https://github.com/dotnet/machinelearning/blob/342e13f8f32279493b3b3e0642a46b2e2690141c/src/Microsoft.ML.Data/Transforms/ColumnBindingsBase.cs#L647)). Therefore, the removal of `ISchema` here can be divided into two steps: (1) Make `ColumnBindingsBase` a standalone class (2) Replace `ColumnBindingBase` with `ColumnBindings` Pete and I had a discussion this morning and we believe this PR can be potentially used as the first step.

---
In reply to: [447128739](https://github.com/dotnet/machinelearning/pull/1868#issuecomment-447128739) [](ancestors = 447128739,446755325,446684574)

---
Refers to: src/Microsoft.ML.Data/Transforms/ColumnBindingsBase.cs:519 in 5e5d342. [](commit_id = 5e5d3424e78824b67060f29fec5c349c86d1b14f, deletion_comment = False)

**Pull request closed without merging**
