### PR TITLE
Attempting to fix M1 tests

### PR DESCRIPTION
**Pull request by ericstj**
We were ignoring failures, remove that and introduce some logging to try to determine what's happening in M1 tests.

### CODE REVIEW

**Comment by ericstj** [comment]
Interesting, so it looks like it tried to load but for some reason that doesn't work.
```
dyld: loaded: <98E9ECD1-4202-3FB2-8191-4D49D08C575A> /private/tmp/helix/working/AE6709D3/w/AC5E09A9/e/libLdaNative.dylib
dyld: unloaded: <98E9ECD1-4202-3FB2-8191-4D49D08C575A> /private/tmp/helix/working/AE6709D3/w/AC5E09A9/e/libLdaNative.dylib
dyld: loaded: <98E9ECD1-4202-3FB2-8191-4D49D08C575A> libLdaNative.dylib
dyld: unloaded: <98E9ECD1-4202-3FB2-8191-4D49D08C575A> libLdaNative.dylib
Finished test: Microsoft.ML.Tests.Transformers.TextFeaturizerTests.LdaWorkout with memory usage 200,458,240.00
Starting test: Microsoft.ML.Tests.Transformers.TextFeaturizerTests.NgramWorkout
[31;1m    Microsoft.ML.Tests.Transformers.TextFeaturizerTests.LdaWorkout [FAIL]
[m[37m      System.DllNotFoundException : Unable to load shared library 'LdaNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libLdaNative, 1): image not found
```
@AaronRobinsonMSFT @elinor-fung do you have a suggestion to get more detail from interop / dlopen to determine why the load is failing?  It looks like the file is present, I've confirmed this by downloading the helix payload.

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-machinelearning-refs-pull-6442-merge-825a1fda38464e0aaf/Microsoft.ML.Tests/1/console.95de5f1c.log?helixlogtype=result

**Comment by AaronRobinsonMSFT** [comment]
> @AaronRobinsonMSFT @elinor-fung do you have a suggestion to get more detail from interop / dlopen to determine why the load is failing? It looks like the file is present, I've confirmed this by downloading the helix payload.

It is entirely possible this is one of those macOS security issues. macOS has specific rules around how `dlopen` is used and the state of the probing path for load at process start. Is the process updating probing paths at run time? I would try to reproduce this locally and use `DYLD_PRINT_LIBRARIES` as suggested. This is unfortunately not an uncommon issue on macOS.

**Comment by ericstj** [comment]
I did set `DYLD_PRINT_LIBRARIES` on the test machine, so all that information should be in the log. https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-machinelearning-refs-pull-6442-merge-825a1fda38464e0aaf/Microsoft.ML.Tests/1/console.95de5f1c.log?helixlogtype=result

**Comment by ericstj** [comment]
As far as I can tell it's finding and trying to load the file, but then rejecting it.  At least that's how I interpret the load/unload.  Is there some data source that could tell us why?  Is there a tool we could use on mac to inspect the binary to make sure it's the right bitness?

**Comment by AaronRobinsonMSFT** [comment]
> As far as I can tell it's finding and trying to load the file, but then rejecting it. At least that's how I interpret the load/unload. Is there some data source that could tell us why?

Is it signed? macOS can get into grumpy about loading unsigned native binaries. I usual determine this by using `Console` on the mac itself and looking at the error, which typically has some mention of "Authentication".

**Comment by ericstj** [comment]
It wouldn't be signed, these are PR validation builds.  So they're built on public azdo machines then pushed to public helix queues.

**Comment by ericstj** [comment]
These binaries are built on one machine and run on another.  I wonder if we need to do that “authorization” on the other machine?  I would expect that dotnet/runtime would face this problem with helix as well 🤔

**Pull request closed without merging**
