### PR TITLE
Removing non source files from solution

### PR DESCRIPTION
**Pull request by Nepomuceno**
According to the discussion on the issue #322 I am proposing removing all non source files from the solution file in order to keep consistency and to keep the solution clean.

### CODE REVIEW

**Comment by sharwell** [comment]
I find it convenient when the files appear in solution explorer, and often wish Roslyn had them. I saw a bug on this recently... one sec I will find it.

**Comment by sharwell** [comment]
On the separate topic of release notes, I would encourage the use of writing them for GitHub Releases rather than placing them in the repository. I find release notes and changelogs in the repository are somewhere between impossible and "unnecessarily tedious" to maintain in the context of branches and tags they are meant to relate to.

**Comment by Nepomuceno** [comment]
I do find that maintaining release notes in the repo it is not the best practice and this should be delegated to the github release notes. but I also find that keeping documentation inside a solution file has similar disadvantages.

It is important though to make a good use of github Issues and use that for the features being implemented if there is a goal of using the realease notes as the changelog and point this release notes to the issues for more details in each one of the changes.

**Comment by shauheen** [comment]
Thanks @Nepomuceno for this PR

**Pull request merged**
