### PR TITLE
Added in note in the documentation that the PredictionEngine is not thread safe.

### PR DESCRIPTION
**Pull request by michaelgsharp**
Since we have had several questions about PredictionEngine and whether its thread safe (#5582 for example), I have just added a small comment to the PredictionEngine class docs saying its not thread safe.

### CODE REVIEW

**Review by ericstj — APPROVED** [review]

**Comment by ericstj** [comment]
@michaelgsharp what does it mean that we see test failure:
```
##[error]XUnit(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Tests failed: /__w/1/s/artifacts/log/Debug/Microsoft.ML.AutoML.Tests_netcoreapp2.1_x64.log [netcoreapp2.1|x64]
```

But no failed tests in the tests tab?  

I see we can download the test results: https://dev.azure.com/dnceng/_apis/resources/Containers/5976716/Ubuntu_x64_NetCoreApp21%20D?itemPath=Ubuntu_x64_NetCoreApp21%20D%2Fartifacts%2Flog%2FDebug%2FMicrosoft.ML.AutoML.Tests_netcoreapp2.1_x64.log

In that log I can see:
```
[33;1m    Microsoft.ML.AutoML.Test.AutoFitTests.AutoFitImageClassification [SKIP]
[m[37m      Takes too much time, ~10 minutes.
[mStarting test: Microsoft.ML.AutoML.Test.AutoFitTests.AutoFitRankingCVTest
Aborted (core dumped)
```

Is this a normal mode of failure for these tests?  Is there any way to look at that dump that was created?

**Comment by michaelgsharp** [comment]
I have always downloaded the logs and not looked in the test tab, but if they aren't showing up there it probably means after the arcade switch we didn't get test logs results uploading correctly. I will look into that.

The most common test failure we have is due to not enough memory and so usually goes away on a re-run. This doesn't say that explicitly, but its probably because of that. We haven't been able to nail all these issues because they only really repro during the CI process, even when we use the same docker image locally. My guess is it has to do with the amount of resource strain on the CI VM, or maybe difference in processor speed? I'll investigate this one more and see what I can find.

**Comment by ericstj** [comment]
I see.  At some point we should consider getting ML.NET onto the same test infrastructure that dotnet/runtime is on.  It has built-in support for collecting dumps, and can benefit from common tooling and docs, reporting (EG: kusto/runfo).  I believe this would mean, move to Helix and use VSTest.  @ViktorHofer @safern does that sound right?

**Comment by michaelgsharp** [comment]
When moving to arcade we saw docs about Helix, so that sounds about right. We talked about doing it at the same time as the move to Arcade, but decided to just focus on that first. I think its a good idea to move at some point as well.

**Comment by ViktorHofer** [comment]
> I believe this would mean, move to Helix and use VSTest. @ViktorHofer @safern does that sound right?

That sounds right. For ML.NET the switch to VSTest should be a no-brainer as requirements are different. The test engine is controlled via the `UseVSTestRunner` property which can be set in the Versions.props file: https://github.com/mono/linker/blob/fc8abeff62398d46ac3408d20f50879e6f2e713f/eng/Versions.props#L31.

When switching to VSTest, it would be a great idea to contribute the existing code coverage (via coverlet) infra back into Arcade and streamline it so that any other repository can use it as well.

Regarding helix, it's a trade-off. There are clear wins when using Helix but they are also clear cons. I recommend to switch to Helix only if there's a strong reason to do so. Runfo works with both AzDO and Helix.

**Comment by michaelgsharp** [comment]
@ericstj @ViktorHofer I will create an issue about the VSTest migration so that I can merge this PR but not lose track of the item.

**Pull request merged**
