### PR TITLE
Sweep Range of L2RegularizerWeight in AveragedPerceptron

### LINKED ISSUE #567: Sweep Range of L2RegularizerWeight in AveragedPerceptron
### Issue

- **What did you do?**
AutoML macro sweep using the AveragedPerceptron learner

- **What happened?**
Crashed due to the AutoML sweeper picking exactly 0.5 for L2RegularizerWeight.

**Error**:
```
  must be in range [0, 0.5)
  Parameter name: L2RegularizerWeight
```

The hyperparameter range need to be changed to exclude 0.5 from its range:
https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/src/Microsoft.ML.StandardLearners/Standard/Online/AveragedLinear.cs#L39

### PR DESCRIPTION
**Pull request by SolyarA**
Fixes #567

### CODE REVIEW

**Comment by justinormont** [comment]
@TomFinley, @Zruty0  : What's the implications of missing the range of 0.4 to 0.5 in L2RegularizerWeight for AveragedPerceptron? 

A better fix for this would be to add a param to the sweep range to note if the range boundaries are inclusive vs. exclusive.

**Comment by Zruty0** [comment]
I cannot say what the implications are, I don't have an intuition on how the optimizer would behave close to 0.5 boundary.

As for inclusive vs. exclusive boundaries: I believe they were originally included in the code (as Min/Max and also Inf/Lim, or something along these lines). But I assume it was deemed unnecessary complexity and removed? I don't find any trace of this anymore.

---
In reply to: [407652667](https://github.com/dotnet/machinelearning/pull/579#issuecomment-407652667) [](ancestors = 407652667)

**Comment by TomFinley** [comment]
I'm not sure "close" to 0.5 is actually a completely sensible value. See here:

https://github.com/dotnet/machinelearning/blob/5e08fa1ea7bfb54f28ed0815cb6413e0068e6dd1/src/Microsoft.ML.StandardLearners/Standard/Online/AveragedLinear.cs#L82-L83

and here:

https://github.com/dotnet/machinelearning/blob/5e08fa1ea7bfb54f28ed0815cb6413e0068e6dd1/src/Microsoft.ML.StandardLearners/Standard/Online/AveragedLinear.cs#L209

Indeed I feel like this is all somewhat haphazard, and whoever introduced this sweep range was making the mistake of confusing sweep range with defining *valid* values... which is not the point at all. Anyway, I'm inclined to just accept @justinormont if that is all right. It seems though like if we *are* going to have continuous values that the notion of inclusive vs. exclusive bounds needs to be accounted for somehow, not sure why such a concept would be removed. 😦

**Comment by justinormont** [comment]
Thanks for pushing in. And thanks @SolyarA for your PR.

@TomFinley: Agreed; we will want to reduce the range of the sweep params from the _valid_ to the _useful_ ranges. This will speed up the hyperparameter optimization. The only reason I see to keep the ranges as wide as the valid is _if_ we can find examples where the extreme values led to good scores. We have further ideas on how to focus the sweeper's energy towards useful ranges of hyperparameters, so perhaps the work of figuring out the useful ranges won't be needed.

**Pull request merged**
