### PR TITLE
Clean up repo

### PR DESCRIPTION
**Pull request by briacht**
Includes:
- Re-organizing and updating main README
- Updating Roadmap
- Adding doc for platform limitations

### CODE REVIEW

**Comment by michaelgsharp** [comment]
Just getting back to this now that I am back in town. It looks good to me. Ready to make it a full PR? Or what is left before you do that?

**Comment by briacht** [comment]
I want to update the roadmap before making it the final draft

**Review by luisquintanilla — APPROVED** [review]
Looks great :)

**Comment by briacht** [comment]
@michaelgsharp This should be good to go!

**Pull request merged**
