### PR TITLE
Rename LinearClassificationTrainer to SdcaBinaryTrainer(#1069)

### LINKED ISSUE #1069: SDCA (LinearClassificationTrainer) should be called SDCA in the codebase
For historic reasons, `SDCA` is named [`LinearClassificationTrainer`](https://github.com/dotnet/machinelearning/blob/044a6d3cf35a8076ecbbcca5cdb61b2f722f94e1/src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs#L1359) in the codebase.

SDCA (Stochastic Dual Coordinate Ascent), while quite good at many datasets, isn't the final answer for linear classification tasks as implied by the `LinearClassificationTrainer` moniker. For example, [`AveragedPerceptron`](https://github.com/dotnet/machinelearning/blob/b88d3460398c5b95745b476e40dd836f8f788cf6/src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs) tends to win on NLP tasks (ngrams and/or chargrams). 

Now is a great time to break with history and call SDCA, simply, `SDCA`.

### PR DESCRIPTION
**Pull request by feiyun0112**
Fix #1069 
Rename LinearClassificationTrainer to SdcaBinaryTrainer, like `SdcaMultiClassTrainer`, `SdcaRegressionTrainer`

### CODE REVIEW

**Comment by Zruty0** [comment]
@sfilipi  could you check if this is consistent with your planned changes?

**Comment by Zruty0** [comment]
@sfilipi  could you check if this is consistent with your planned changes?

**Comment by sfilipi** [comment]
Thanks for the contribution, @feiyun0112

---
In reply to: [434943448](https://github.com/dotnet/machinelearning/pull/1417#issuecomment-434943448) [](ancestors = 434943448)

**Comment by sfilipi** [comment]
Yep, we will go with the longer form.

**Pull request merged**
