### PR TITLE
Run formatting on src projects

### PR DESCRIPTION
**Pull request by jwood803**
Run `dotnet format` on all projects in the `src` directory for formatting.

cc// @michaelgsharp 

Updates #302

### CODE REVIEW

**Review by michaelgsharp — APPROVED** [review]
LGTM. I coudln't get the code coverage build to run, so I just restarted them all. Once they finish I can merge it in.

**Comment by jwood803** [comment]
Closing and reopening to see if builds will rerun

**Comment by michaelgsharp** [comment]
@jwood803 the code coverage upload step is failing, which is what is blocking the build. I have been looking into it the last couple of days and I think I have the solution. Just making sure its an OK to solution to use. As long as I get the OK to go ahead with it, should be resolved by later today.

**Pull request merged**
