### PR TITLE
Made loop bound checking in hardware intrinsics more efficient

### LINKED ISSUE #835: CpuMath Enhancement: Make bound checking of loops in hardware intrinsics more efficient
Style changes needed to solve part of https://github.com/dotnet/machinelearning/issues/823

## Details
-  In `src\Microsoft.ML.CpuMath\SseIntrinsics.cs` and `src\Microsoft.ML.CpuMath\AvxIntrinsics.cs`, changing `while (pDstCurrent + 4 <= pDstEnd)` for the loop bound checking into `while (pDstCurrent <= pDstEnd - 4)` to save an instruction (ref: https://github.com/dotnet/machinelearning/pull/668#issuecomment-412121893)
- It may probably be a CoreCLR issue

### PR DESCRIPTION
**Pull request by cTxplorer**
Changed style to make loop bound checking more efficient.

Closes #835

### CODE REVIEW

**Comment by cTxplorer** [comment]
@codemzs No, I don't have benchmark numbers.

**Comment by danmosemsft** [comment]
@cTxplorer thanks for doing this.

It may be that the JIT cannot currently even figure out that `pEnd` is a constant during the loop, so this does not save any work. It would probably be better to extract out something like `var pEndMinus8 = pEnd - 8` and then you can do `while (pDstCurrent <= pEndMinus8)`. 

That may be worth doing but benchmarking will say for sure. To benchmark you need to build for .NET Core 3.0 since this codepath is not used otherwise. Hopefully @eerhardt can [help me with this](https://github.com/dotnet/machinelearning/issues/1011). 

After that instructions to run the benchmarks are [here](https://github.com/dotnet/machinelearning/blob/master/test/Microsoft.ML.Benchmarks/README.md) although again there will be some flag required to make sure it runs on .NET Core 3.0

Thanks for your patience (this is probably more complex than you expected)

cc @tannergooding

**Comment by danmosemsft** [comment]
Instructions for building on 3.0 are here: https://github.com/dotnet/machinelearning/pull/1032

**Comment by shauheen** [comment]
Thanks @cTxplorer for looking at this, do you have any plans to update this PR?

**Comment by tannergooding** [comment]
@cTxplorer, the merge conflicts need to be resolved and the same feedback made in https://github.com/dotnet/machinelearning/pull/1177 applies here (which is a smaller, but related PR).
* The primary feedback is that `pDstEnd - <const>` needs to be pulled out into a local to ensure that it isn't done once per loop iteration.

**Comment by danmosemsft** [comment]
@cTxplorer please also share benchmark results, as in #1177.

**Comment by danmosemsft** [comment]
@cTxplorer could you clarify the purpose of the rename (81401e9) ? It seems that was intended for a separate PR, associated with some other issue. (And if renamed, probably the file should be too). We would like to keep each PR for a single purpose to keep things clear. Thanks

**Comment by danmosemsft** [comment]
cc @jwood803

**Comment by tannergooding** [comment]
@cTxplorer, going to close this for now since we haven't had any update in over 10 days.

If you would like to continue working on this, feel free to open a new PR that resolves the conflicts and we will be happy to help push it through.

**Pull request closed without merging**
