### PR TITLE
Add missing implementation for datetime relevant arrow type into dataframe

### LINKED ISSUE #6201: Add missing implementation for datetime relevant arrow types
At the moment, it is not possible to create a dataframe containing datetime columns using the static method DataFrame FromArrowRecordBatch(RecordBatch recordBatch)
This will be helpful for loading a recordBatch using Apache Arrow

The method can be extended to support datetime colums. 
It might be useful to check which types are already implemented in Aoache.Arrow
https://github.com/apache/arrow/blob/master/csharp/src/Apache.Arrow/Arrays/ArrowArrayFactory.cs

### PR DESCRIPTION
**Pull request by asmirnov82**
Fixes #6201

Add support for converting Apache Arrow Date64 column into DataFrame DateTimePrimitiveColumn and vice versa

### CODE REVIEW

**Review by michaelgsharp — APPROVED** [review]
LGTM. Thanks for submitting this!

**Comment by JakeRadMSFT** [comment]
Merged into Generic Math branch.

**Pull request merged**
