### PR TITLE
Remove Excessive Logging from SymSgdClassificationTrainer

### LINKED ISSUE #5598: SymSGD Excessively Verbose
Remove logging line, or modify from `ch.Info` to `ch.Trace`:
https://github.com/dotnet/machinelearning/blob/5dbfd8acac0bf798957eea122f1413209cdf07dc/src/Microsoft.ML.Mkl.Components/SymSgdClassificationTrainer.cs#L813

For my text dataset, this logging line dumps ~100 pages of floats to my console. That level of verbosity is unneeded at the `Info` level.

I'd recommend just removing the logging line.

### PR DESCRIPTION
**Pull request by x-danma**
Fixes #5598 

I have removed the logging statement as suggested by the issue reporter, and have adjusted the affected BaseLineOutput files for Microsoft.ML.Predictor.Tests.

We are excited to review your PR.

The lo
So we can do the best job, please check:

- [X] There's a descriptive title that will make sense to other developers some time from now. 
- [X] There's associated issues. All PR's should have issue(s) associated - unless a trivial self-evident change such as fixing a typo. You can use the format `Fixes #nnnn` in your description to cause GitHub to automatically close the issue(s) when your PR is merged.
- [X] Your change description explains what the change does, why you chose your approach, and anything else that reviewers should know.
- [X] You have included any necessary tests in the same PR.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=6001) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=6001) before we can accept your contribution.<br/><br/>:x: x-danma [sign now](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=6001)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/machinelearning?pullRequest=6001) it.</sub>

**Comment by x-danma** [comment]
The three commits from my fork is an unfortunate are supposed to be just one, but got a branch merge when trying to rename my commit with the issue number.

**Review by michaelgsharp — APPROVED** [review]
:shipit: LGTM. I'll get it merged in.

**Comment by justinormont** [comment]
@x-danma: thanks for the fix.

**Comment by x-danma** [comment]
Thanks for the opportunity! This was my first OSS contribution.

**Pull request merged**
