### PR TITLE
Disable test parallelization in TimeSeries tests

### PR DESCRIPTION
**Pull request by sharwell**
Extracted from #4569

### CODE REVIEW

**Comment by frank-dong-ms** [comment]
what is the purpose of disabling test parallelization in TS tests?

**Comment by sharwell** [comment]
I meant to make this one a draft PR. I'm not certain it's correct but didn't want to lose track of the commit during a rebase.

**Comment by harishsk** [comment]
Do we still need to keep this PR open?

**Comment by mstfbl** [comment]
Hi @sharwell , I've converted this PR to a draft PR as you said you meant to. Feel free to close the PR if you don't need it open anymore. Thanks.

**Pull request closed without merging**
