### PR TITLE
Update to Preview5 of .NET Core 3.0

### PR DESCRIPTION
**Pull request by eerhardt**
Updating to the latest release version of .NET Core 3.0.

### CODE REVIEW

**Comment by danmosemsft** [comment]
An existing error @shauheen  ?

```
SlidingWindowTransformBase.cs(140,26): error CS8511: An expression of type 'SlidingWindowTransformBase<TInput>.BeginOptions' cannot be handled by a pattern of type 'SlidingWindowTransformBase<TInput>.BeginOptions'. Please use language version 'preview' or greater to match an open type with a constant pattern. [/__w/1/s/src/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.csproj]
SlidingWindowTransformBase.cs(143,26): error CS8511: An expression of type 'SlidingWindowTransformBase<TInput>.BeginOptions' cannot be handled by a pattern of type 'SlidingWindowTransformBase<TInput>.BeginOptions'. Please use language version 'preview' or greater to match an open type with a constant pattern. [/__w/1/s/src/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.csproj]
/__w/1/s/dir.traversal.targets(25,5): error : Build failed. See earlier errors. [/__w/1/s/build.proj]
```

**Comment by eerhardt** [comment]
Looks to be https://github.com/dotnet/roslyn/issues/34905

cc @gafter @agocke - is this bug going to be fixed in Preview5?

**Comment by agocke** [comment]
Assuming it's the same bug, yes, the fix should be in Preview 5

**Comment by eerhardt** [comment]
@tannergooding - I've updated the tests to account for the new formatting changes in 3.0. The changes were of the form:

BEFORE
```
2	402.2	401.212952	0.987060546875	0.97428852319717407
```

AFTER
```
2	402.2	401.21295	0.987060546875	0.97428852319717407
```

However, there is one test problem that I haven't solved yet. It is causing about 4 tests to fail. The issue is comparing the baseline number (netfx and netcoreapp2.1 behavior) format:

```
3.40282347E+38
```

To the new netcoreapp3.0 format:

```
3.4028235E+38
```

The current `CompareNumbersWithTolerance` behavior only seems to take into account decimals, and not digits in the exponential form. Any thoughts on how to fix this? (I assume this behavior change in 3.0 is intentional.)

**Comment by danmosemsft** [comment]
Updated to today's Preview 5 build since why not test it.

**Comment by danmosemsft** [comment]
@tannergooding could you please help @eerhardt get this green? It helps us validate and protect Preview 5.

(Up to @shauheen whether he actually submits this or hold it for //BUILD but either way we get benefit)

**Comment by eerhardt** [comment]
@tannergooding and I sync'd up last night on this. We have a plan for fixing the current failing tests, and I will also log an issue to attempt to address this issue in a better manner long term.

**Comment by eerhardt** [comment]
@tannergooding - I've implemented the approach we discussed. Can you take a look?

I've opened https://github.com/dotnet/machinelearning/issues/3589 to track using this new approach in more places.

**Comment by tannergooding** [comment]
The changes LGTM for the initial fix.

**Comment by eerhardt** [comment]
@shauheen - is `master` open for post-1.0 checkins? I believe this is ready to be merged.

**Pull request merged**
