### PR TITLE
Docs formatting

### PR DESCRIPTION
**Pull request by sfilipi**
Incorporating the changes the content developing team made to the ml.net doc repo: https://github.com/dotnet/ml-api-docs

### CODE REVIEW

**Comment by Ivanidzo4ka** [comment]
@dotnet-bot test VSTS: public-CI

**Comment by Ivanidzo4ka** [comment]
@dotnet-bot test this

**Comment by sfilipi** [comment]
@dotnet-bot test this again

**Comment by Ivanidzo4ka** [comment]
@eerhardt  you mentioned this morning what "@dotnet-bot test this" suppose to work, but it doesn't work for me and @sfilipi , Can you show proper spelling?

**Comment by eerhardt** [comment]
@Ivanidzo4ka - sorry.  I was wrong this morning.  @mmitche told me that the only way to re-run a `VSTS: public-CI` leg is to push a new commit.  The VSTS team is currently working on enabling this.

A couple tricks to pushing a new commit:
1. in Team Explorer, View History on a branch.  then you can see your latest commit.  double click that.  or right -click View Details. you will see the commit message, edit it somehow. and click Amend Message.  Then `git push -f` to push the amended commit.
2. Alternatively, you can create a new empty commit with `git commit --allow-empty -m "Trigger"`

Doing either of the above will re-run the tests.

**Pull request merged**
