### PR TITLE
Basic Agglomerative clustering implementation  #5725

### PR DESCRIPTION
**Pull request by Srujana-Oruganti**
#5725
Basic Agglomerative clustering implementation:
1. Implement basic agglomerative clustering.
2. Distance measure is Euclidean distance.
3. Included 3 Linkage Criteria implementations : Single Link, Complete Link, Average Link.
4. Simple testcase

ToDo:
1. Implement other Linkage Criteria like: Ward, Centriod based linkage.
2. Add support for other distance metrics.
2. Implement agglomerative clustering using efficient heap based approach.
3. Implement model saving and reloading.
4. Implement visualization of dendrogram.
5. Implement cluster prediction capability.
6. Include more test cases.
7. Refactor common code for different Clustering projects to a common project.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=6018) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=6018) before we can accept your contribution.<br/><br/>:x: Srujana-Oruganti [sign now](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=6018)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/machinelearning?pullRequest=6018) it.</sub>

**Comment by michaelgsharp** [comment]
@Srujana-Oruganti sorry for the delay on this. Thanks for taking the time to submit it. It looks good! Is this something you are still interested in working with us on? Looks like the build issue is from not being able to load the model. I'm looking into that a bit to see if I can figure it out easily.

**Comment by michaelgsharp** [comment]
Closing due to stale PR.

**Pull request closed without merging**
