### PR TITLE
Update error messages to point to GitHub issues instead of support group

### PR DESCRIPTION
**Pull request by jwood803**
Fix for issue #258 by replacing `tlcsupp` with a link to https://aka.ms/MLNetIssue.

Due to my lacking git skills, some commits from #358 got in, but I believe that can get cleaned up if/when it gets merged.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Hi @jwood803, you should be able to eliminate the extra changes by either rebasing your branch onto master, or merging master into your branch.

If you do the former (what I typically do) you will have to `git push -f` to update this PR, other wise you can just `git push`.

You're probably right that on merging, the changes should vanish, but if they do not entirely vanish, they are then committed to master, so it is best to have the PR look how you want it.

**Comment by jwood803** [comment]
Thanks, @danmosemsft! I'll make sure to remember that for next time. 😄 

Hopefully, the PR is as it should be.

**Comment by danmosemsft** [comment]
@jwood803 assuming you only wanted to make the comment changes, this didn't work, as they still show up: https://github.com/dotnet/machinelearning/pull/359/files

My instructions were mistaken, then. I think what is easiest is you just do `git reset --hard master` (this will lose all your changes, but keep you on the branch for this PR) then make the change manually, commit, and `git push -f`. Does that do it?

**Comment by jwood803** [comment]
@danmosemsft Thanks a ton! I had to reset to upstream master, but I think I now got this correct! 😄 Thanks again for the help!

**Comment by shauheen** [comment]
Thanks @jwood803 for this PR.

**Pull request merged**
