### PR TITLE
Implement MSML_RelaxTestNaming suppressor for VSTHRD200

### PR DESCRIPTION
**Pull request by sharwell**
Allow asynchronous test methods to omit the 'Async' suffix.

### CODE REVIEW

**Comment by sharwell** [comment]
@harishsk for reviews

**Comment by sharwell** [comment]
Or @justinormont

**Comment by harishsk** [comment]
Is this PR to allow tests that have await calls within them to not be forced to have an Async suffix for the function name?

Also, can you please resolve the merge conflicts?

**Comment by sharwell** [comment]
> Is this PR to allow tests that have await calls within them to not be forced to have an Async suffix for the function name?

Yes, that is correct.

**Pull request merged**
