### PR TITLE
[WIP] Add GPU package of tensorflow

### PR DESCRIPTION
**Pull request by ericstj**
Issue #871

Best reviewed commit-by-commit.

This adds a GPU build package for tensorflow and attempts to use it for tests.

I'm not certain yet about the mechanism for opting into the GPU build, this was really just a sample to see what we could do.

### CODE REVIEW

**Comment by ericstj** [comment]
Note I expect that this will fail CI due to lack of NVIDIA dependencies.

**Comment by zeahmed** [comment]
Can you please specify the version information of CUDA and CuDNN that these dll will be supporting? or the link that you shared earlier will also be help.

**Comment by zeahmed** [comment]
Also, were you able to work the dll in windows? I am able to load it.

---
In reply to: [420474818](https://github.com/dotnet/machinelearning/pull/890#issuecomment-420474818) [](ancestors = 420474818)

**Comment by ericstj** [comment]
I haven't gotten that far yet.  Just got builds working and was going to look at tests but had to leave.

Here's the statically imported DLLs from this TF build:
```
cusolver64_90.dll
cublas64_90.dll
nvcuda.dll
cudnn64_7.dll
cufft64_90.dll
curand64_90.dll
cudart64_90.dll
```

I'll find out which dependencies these translate to and update package info.

---
In reply to: [420477318](https://github.com/dotnet/machinelearning/pull/890#issuecomment-420477318) [](ancestors = 420477318,420474818)

**Comment by ericstj** [comment]
OK, so all those 90's in the filename are important.  Those mean that this build of TF *requires* the 9.0 version of CUDA, 9.2 will not cut it.  

To get the 9.0 version you need to download it from [https://developer.nvidia.com/cuda-90-download-archive](https://developer.nvidia.com/cuda-90-download-archive)

And for cuDNN you need the corresponding one here: [https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v7.2.1/prod/9.0_20180806/cudnn-9.0-windows10-x64-v7.2.1.38](https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v7.2.1/prod/9.0_20180806/cudnn-9.0-windows10-x64-v7.2.1.38)

Testing these out and will report back.

---
In reply to: [420706286](https://github.com/dotnet/machinelearning/pull/890#issuecomment-420706286) [](ancestors = 420706286,420477318,420474818)

**Comment by zeahmed** [comment]
Thanks @Eric, Have you tested it out? I haven't been able to load this particular GPU dll. I have correctly set all the dependencies. It seems like its probably because of some dependencies are not satisfied. Whats the best way identify which dependency is missing. I am always getting `DLL not found` error?

---
In reply to: [420739038](https://github.com/dotnet/machinelearning/pull/890#issuecomment-420739038) [](ancestors = 420739038,420706286,420477318,420474818)

**Comment by ericstj** [comment]
Yeah, I was able to get it to work.  You should double check that these DLLs are on the path.  You can do so by typing "where <dllName>" from the command prompt.

Since cuDNN is a zip you have to make sure you extract it somewhere on the path.  I chose to put it in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin next to the rest of CUDA.  I then made sure that CUDA was on the path (it may or may not be depending on what you selected when installing it) and made sure that the process trying to load it had the updated path (it may not if the process tree launching it was running before the PATH was modified).

You also need to make sure you have the VC runtime installed, but that dependency is the same as the CPU build of TF so its likely not causing you issues.  If you're still running into issues we can do a screen sharing session and I'll help you resolve them.

Even though I got this to work the experience was pretty bad.  Even once it was working I found sporadic failures when running the unit tests, usually around TF failing to allocate memory on the card or failing to open a handle, etc.  Is this flakiness something normal with TF or could it point to a problem with the ML.NET transform (eg: failing to close sessions).

---
In reply to: [421089145](https://github.com/dotnet/machinelearning/pull/890#issuecomment-421089145) [](ancestors = 421089145,420739038,420706286,420477318,420474818)

**Comment by zeahmed** [comment]
I think everything is set properly because Tensorflow python version works perfectly fine. I will talk you separately on this.

There are memory errors when GPU card memory is not enough for the operation being performed. Since ML.Net tests are not that big so assume its not because of that. Its something related to dll or platform itself.

---
In reply to: [421118412](https://github.com/dotnet/machinelearning/pull/890#issuecomment-421118412) [](ancestors = 421118412,421089145,420739038,420706286,420477318,420474818)

**Comment by TechnikEmpire** [comment]
Has anyone fully considered the legalities here? Here's one example of a project that still can't figure out exactly how to sell their souls to Nvidia, even after 2 years of discussion:

https://github.com/conda-forge/conda-forge.github.io/issues/63

And googling "cuda" + "clickwrap" will yield many more such discussions.

**Comment by ericstj** [comment]
Thus the WIP on this PR.  I think there are quite a few rough edges with the GPU build right now that would block us redistributing, legal included.  Right now the approach isn't much different than what we were doing for the TF binaries, but it would need to undergo legal signoff.  **IF** we decided to *redist* NVIDIA binaries rather than rely on the developer to *bring their own* that would require a whole new round of legal / license review, and likely much more packaging work.

**Comment by ericstj** [comment]
I suspect we should just close this PR without merging since it's not currently a solution we want to ship.  @yaeldekel what do you think?

**Comment by TechnikEmpire** [comment]
C++ AMP. C'mon you guys can do it! Anyway on a serious note, maybe accelerated packages should just be community add-ons, or people fork opencv dnn package in. If Intel open sources openvino and fixes amd support then that could be an alternative, as it's stupidly fast and exceeds many gpu implementations. Etc etc words you get the point.

**Comment by TechnikEmpire** [comment]
What are the rules about mixing in code with another license for this repo? A third party dep. I think it might be possible to have this with an OpenCL 1.2 driven backend rather than CUDA without modifying TF source if bringing in an Apache2 third-party dep is acceptable.

**Comment by ericstj** [comment]
I was more concerned with the fragility of the setup rather than the licensing.  We look at TF as a third party dependency that we're just helping people deploy.  We just expose its own licenses in the NuGet package and then package it in way friendly to the NuGet conventions/.NET.

The thing that's bothering me about the GPU build is that:
1) It has additional dependencies with rather heavy installers.  Heavy in the sense that they install much more than is needed, require admin, and install drivers on the machine.
2) Those installers don't fully configure the machine for TF to load their binaries so even after installing these you need manually setup the path (and even manually copy files).
3) It requires very specific versions of those installers which aren't compatible with other versions.

**Comment by TechnikEmpire** [comment]
Thanks for the response. Is it necessary to include driver installation as a packaging requirement? It would seem that most of your concerns can be settled by leaving it up to the user. From a developer's position, I think it's perfectly reasonable to kick that can down the road. Were I developing an application I plan to ship into the market, I'd be doing checks at the install phase to see if the system is correctly configured to run my software.

**Comment by ericstj** [comment]
That's typically not the expectation of folks using NuGet and .NET.  Most of the time you expect to be able to install a package and try it out.  I question how much value we really add by producing a package and still having all these manual steps.

How is that any better from just adding one more manual step (download and unzip the TF GPU binary) instead of this package?

**Comment by TechnikEmpire** [comment]
Maybe I misunderstood some terms. When you say that ensuring drivers are installed, are you saying that the nuget package should ensure that CUDA and current Nvidia drivers etc etc are installed?

**Comment by Zruty0** [comment]
I agree with @ericstj , we should close this and have an issue for a less fragile solution.

**Comment by ericstj** [comment]
And just to clarify, I wasn't taking issues with drivers and setup etc etc.  I was just saying that to get the tensorflow-GPU build working you need to do N things many of which are non-trivial.  Having us provide a nuget package only makes that N-1, where the one thing we alleviate is arguably trivial (download a binary).  As such I don't see it as really moving the bar substantially at enabling the scenario, and it would be a source for bugs when folks ask for support on the N-1 steps.

**Comment by TechnikEmpire** [comment]
I build deep learning packages from scratch by hand all the time, often bypassing the bundled build system and at this point it just sounds like words being typed to not admit you never had a point to begin with. There's drivers and binaries that rely on those drivers. Period. This PR is garbage and can't be shipped to the mass market because it's hardware specific. I'm not sure why you came out so strongly talking to me like I'm an idiot in order to defend your position. Maybe you did all this on company time and have to explain away why money just got flushed down the toilet.

Woulda been better to leave it alone instead of coming back and doubling down on it.

**Pull request closed without merging**
