### PR TITLE
changes in code info to trace and remove the line   Bias: -456.6284, Weights: [0.1279876,32.69715,-3.546452,-0.4864577,-19.49884,12.29909,-6.273879,13.22529,21.40667] 

### PR DESCRIPTION
**Pull request by bhargavsonagara**
We are excited to review your PR.

So we can do the best job, please check:

- [ ] There's a descriptive title that will make sense to other developers some time from now. 
- [ ] There's associated issues. All PR's should have issue(s) associated - unless a trivial self-evident change such as fixing a typo. You can use the format `Fixes #nnnn` in your description to cause GitHub to automatically close the issue(s) when your PR is merged.
- [ ] Your change description explains what the change does, why you chose your approach, and anything else that reviewers should know.
- [ ] You have included any necessary tests in the same PR.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5912) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5912) before we can accept your contribution.<br/><br/>:x: bhargavsonagara [sign now](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5912)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/machinelearning?pullRequest=5912) it.</sub>

**Comment by michaelgsharp** [comment]
Looks like there are several more baseline files that will need to be edited. The ones I saw when glancing at the test output are gonna be found in `test\BaselineOutput\Common\SymSGD\win-x86` and `test\BaselineOutput\Common\SymSGD\win-x64` but there may  be some I didn't see. Can you remove the same line from those baseline files as well?

**Comment by bhargavsonagara** [comment]
> Looks like there are several more baseline files that will need to be edited. The ones I saw when glancing at the test output are gonna be found in `test\BaselineOutput\Common\SymSGD\win-x86` and `test\BaselineOutput\Common\SymSGD\win-x64` but there may be some I didn't see. Can you remove the same line from those baseline files as well?

which line i didn't understand?

**Comment by michaelgsharp** [comment]
Thanks for taking the time to do this! The line of code that was causing this issue has been entirely removed. Closing this pr as its no longer need.

**Pull request closed without merging**
