### PR TITLE
Fixed all typos in word `Transform`.

### PR DESCRIPTION
**Pull request by JoshuaLight**
Hey guys!

Wanna trying to contribute and do some helpful work! What is my first small trophy — typo in `ILearningPipelineStep` comment, which, as I found, is presented in other places in code.

### CODE REVIEW

**Comment by TomFinley** [comment]
@dotnet-bot test OSX10.13 Release

**Comment by JoshuaLight** [comment]
Wow! It seems like some of commits from my repo silently appeared in this PR, so I'll revert them.

**Comment by JoshuaLight** [comment]
Done!

**Comment by TomFinley** [comment]
@dotnet-bot test OSX10.13 Release

**Pull request merged**
