### PR TITLE
Handle case where there are no input transforms

### PR DESCRIPTION
**Pull request by mjmckp**
Pipeline with no data transforms will throw an exception on the line below, as `input.TransformModels` has length zero.

### CODE REVIEW

**Comment by Ivanidzo4ka** [comment]
Any chance you can create issue with example, and unit test to cover this case?

**Comment by Ivanidzo4ka** [comment]
I also address this problem in #172  For combiner I would rather modify check for transforms, instead of 
`host.CheckNonEmpty(input.TransformModels, nameof(input.TransformModels));`
to
` host.Check(Utils.Size(input.TransformModels) > 0, nameof(input.TransformModels));`

**Comment by mjmckp** [comment]
@Ivanidzo4ka So does #172 fully address this issue, or do we need this change as well?

**Comment by Ivanidzo4ka** [comment]
It address the issue. You can try to run your code with new nuget, it should work

---
In reply to: [389730271](https://github.com/dotnet/machinelearning/pull/178#issuecomment-389730271) [](ancestors = 389730271)

**Comment by mjmckp** [comment]
Ok, thanks a lot @Ivanidzo4ka

**Pull request closed without merging**
