### PR TITLE
WIP: Fixed column name\order in iris dataset

### PR DESCRIPTION
**Pull request by OliaG**
per issue #400 
Fixed the iris dataset

### CODE REVIEW

**Comment by OliaG** [comment]
I have switched the order and the name of two columns. Not sure, why it affected acc metric. @Ivanidzo4ka , @codemzs is that expected?

**Comment by codemzs** [comment]
Hi Olia,
public class IrisData
        {
            [Column("0")]
            public float Label;

            [Column("1")]
            public float SepalLength;

            [Column("2")]
            public float SepalWidth;

            [Column("3")]
            public float PetalLength;

            [Column("4")]
            public float PetalWidth;
        }

You will need to update the order in which values are passed during prediction as well to ensure the ACC metrics are same. Do we really need to change the order? 

---
In reply to: [400119754](https://github.com/dotnet/machinelearning/pull/408#issuecomment-400119754) [](ancestors = 400119754)

**Comment by TomFinley** [comment]
Hi thanks @OliaG ... incidentally could we perhaps make changes in *forks* of this repository, rather than in this repository itself?

**Comment by bojanmisic** [comment]
I wanted to jump in and tackle this one as my first bug fix, but @OliaG it's yours :).

I believe that also tests (_TrainAndPredictIrisModelTest_ and _TrainAndPredictIrisModelWithStringLabelTest_) should be modified to have more realistic values when testing prediction (since those are shifted there as well). This is where I have encountered some strange behavior: for values **(SepalLength, SepalWidth, PetalLength, PetalWidth) = (4.4, 3.1, 2.5, 1.2)** predictions when the label is string (_TrainAndPredictIrisModelWithStringLabelTest_) and when the label is numeric (_TrainAndPredictIrisModelTest_) were different dramatically - I still haven't figured out if I was causing it for some reason (the dataset modifications were done the same way you did).

**Comment by shauheen** [comment]
@OliaG as Tom mentioned it would be great if you would do the PR against a fork. Can we perhaps close this PR (remove the branch) and take a PR against @bojanmisic fork?

**Comment by OliaG** [comment]
@shauheen sure, let's do it. I'll close this PR and @bojanmisic can create his. Also we will need to update our samples repo: [classification](https://github.com/dotnet/machinelearning-samples/tree/master/samples/getting-started/MulticlassClassification_Iris) and [clustering](https://github.com/dotnet/machinelearning-samples/tree/master/samples/getting-started/Clustering_Iris) examples that are using the same dataset. @bojanmisic you're welcome to do that too or I can do it.

**Comment by bojanmisic** [comment]
@OliaG, PR created: #428. The fix for samples repo will follow. Thanks!

**Pull request closed without merging**
