### PR TITLE
Use APICompat from the SDK

### PR DESCRIPTION
**Pull request by ericstj**
We're using the 7.0 RC2 SDK which has support for multiple assembly packages.

### CODE REVIEW

**Comment by tarekgh** [comment]
```
/Users/runner/work/1/s/Microsoft.ML.sln(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
  Determining projects to restore...
  Restored /Users/runner/work/1/s/src/Native/Native.proj (in 203 ms).

Build FAILED.

/Users/runner/work/1/s/Microsoft.ML.sln(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
    0 Warning(s)
    1 Error(s)
```

**Comment by ericstj** [comment]
Yeah, fixing that.

**Comment by ericstj** [comment]
This should be working now.

**Review by tarekgh — APPROVED** [review]

**Review by smasher164 — APPROVED** [review]
LGTM

**Comment by michaelgsharp** [comment]
@ericstj Target framework .NETStandard,Version=v2.0 is no longer supported in the latest version.

**Comment by ericstj** [comment]
> @ericstj Target framework .NETStandard,Version=v2.0 is no longer supported in the latest version.

Yeah, that error was happening because we removed the empty assembly in https://github.com/dotnet/machinelearning/commit/c55727ce3b50adbf034c97e8a8978fb1c58eea3b.

I've suppressed it since that removal doesn't actually impact customers: they'll still be able to install the package and it will provide all the same functionality.

**Pull request merged**
