### PR TITLE
Fixes #128

### LINKED ISSUE #128: 'Type not implemented or supported' exception message from TextLoader is not descriptive
### Issue

- I added ml package for the first time and tried to customize a tutorial a bit
- I got 'Type not implemented or supported' exception. I did not understand what type is not supported and wasted a lot of time and ended up on github, looking for answers
- I would like to know, what type is actually not supported yet. It would simplify a learning curve and save me some nerves.

### PR DESCRIPTION
**Pull request by v-tsymbalistyi**
Make a 'not supported field type' exception more readable, so the developer could figure out why he can't load the data. This should make learning curve smoother for an incoming developer

### CODE REVIEW

**Comment by glebuk** [comment]
thanks! looks good.

**Comment by shauheen** [comment]
Thanks for this contribution. Please for future PRs make sure that the title has something about the work done rather than just referencing the issue.

**Comment by v-tsymbalistyi** [comment]
Oh... Sure!
Thanks for the feedback @shauheen

**Comment by shauheen** [comment]
cheers :)

**Pull request merged**
