### PR TITLE
Update build tools version and use netcoreapp3.0 on ubuntu CI

### LINKED ISSUE #2381: Add Ubuntu CI leg
Right now we build and test for Linux on only one distro -- Centos 7 (a container hosted on Ubuntu 1804). We use .NET Core 2.1.

We maybe should add a leg to test on a Debian/Ubuntu family distro (Centos is in the RedHat family). That should be able to use all the same binaries. If we did that it would probably be good to use .NET Core 3.0 instead of 2.1 to get Linux coverage with that.

.NET Core also supports Alpine, which some people use to minimise the size and security surface of their containers. It would be more "interesting" (takes= more work to support) because as well as having few default packages it is musl not glibc based so it needs a special build. We probably have to defer support for Alpine.

@eerhardt thoughts?

### PR DESCRIPTION
**Pull request by Anipik**
Fixes #2381 

Updates the buildtools version to latest and also running tests and building machinelearning repo with netcorepp3.0 on non-windows machine

### CODE REVIEW

**Comment by Anipik** [comment]
@safern one of ubuntu configuration(Debug) is netcoreapp2.1

**Comment by Anipik** [comment]
@tannergooding 
i am trying to use these flags COMPlus_EnableAvx and COMPlus_EnableSse on ubuntu netcoreapp3.0, these flags are getting set but Avx.IsSupported and Sse.IsSupported is still coming out to be true
​
do we need to do something else here ?

**Comment by tannergooding** [comment]
@Anipik pinged me offline, the issue was with the casing of the Environment Variables. They work on Windows, but not on Unix because Windows is case-insensitive (most of the time) and Unix is case-sensitive (also, most of the time).

**Comment by Anipik** [comment]
@eerhardt can you review this one ? thanks :)

**Pull request merged**
