### PR TITLE
Remove Lotus references.

### LINKED ISSUE #19: Remove/Rename LotusIR namespace
_From @KrzysztofCwalina on Apr 16, 2018, 9:13 AM PDT_

There is a public top level LotusIR namespace in our repo. We agreed that all our namespaces will be in Microsoft.MachineLearning, and so we should rename or remove this LotusIR namespace.

### PR DESCRIPTION
**Pull request by codemzs**
fixes #19

### CODE REVIEW

**Comment by TomFinley** [comment]
Please see also the following files.

```
src/Microsoft.ML.Data/Prediction/Calibrator.cs
src/Microsoft.ML.Data/Transforms/TransformBase.cs
src/Microsoft.ML.Transforms/NormalizeTransform.cs
src/Microsoft.ML.FastTree/TreeEnsemble/RegressionTree.cs
src/Microsoft.ML.FastTree/FastTree.cs
```

**Comment by TomFinley** [comment]
That is not what I am suggesting. You're cleaning up this Lotus stuff. Look in the files. You will see references to LotusVNext. E.g.:

https://github.com/dotnet/machinelearning/blob/9f3076df0d7a7f3ebccc53e0602fa30b90a897fc/src/Microsoft.ML.Data/Prediction/Calibrator.cs#L1352

You're removing the support code for this LotusIR, remove all of it please. Thanks.

**Comment by codemzs** [comment]
I'm NOT cleaning lotus stuff. For the second time, I'm fixing issue# 19 which is removing or renaming LotusIR namespace from top-level namespace. What you are suggesting is a new a issue which needs to be filed and worked on a separate PR.

---
In reply to: [392904328](https://github.com/dotnet/machinelearning/pull/252#issuecomment-392904328) [](ancestors = 392904328)

**Comment by codemzs** [comment]
Hi Tom,

I want to clarify that I'm not cleaning up Lotus stuff. I'm addressing issue# 19 which says to remove or rename LotusIR namespace since it is a top level-level namespace and not in Microsoft.ML as agreed up one. LotusIR namespace is only used in the code generated proto file which is not being used anywhere so it is safe to remove LotusIR namespace and the delete the file. I think this addresses issue#19 which is what I was targeting. 

What you are suggesting is also a valid issue which we should address but it is not part of #19. I will be happy to create an issue for cleaning up Lotus references and include in this PR. We can chat more offline.

---
In reply to: [392904328](https://github.com/dotnet/machinelearning/pull/252#issuecomment-392904328) [](ancestors = 392904328)

**Comment by TomFinley** [comment]
If there is an issue that said, "remove X," then yes, the absolute implication is that at the same time code or content that can serve absolutely no practical purpose whatsoever *except* to service X should also be removed, at the same time. To claim we need a separate issue filed for it verges on pedantry. Just fix it please.

---
In reply to: [392917717](https://github.com/dotnet/machinelearning/pull/252#issuecomment-392917717) [](ancestors = 392917717,392904328)

**Comment by codemzs** [comment]
Done.

---
In reply to: [392930279](https://github.com/dotnet/machinelearning/pull/252#issuecomment-392930279) [](ancestors = 392930279,392917717,392904328)

**Pull request merged**
