### PR TITLE
Added in release notes for 3.0.1

### PR DESCRIPTION
**Pull request by michaelgsharp**
Adding in release notes for 3.0.1

### CODE REVIEW

**Review by ericstj — APPROVED** [review]
🚢

**Comment by michaelgsharp** [comment]
Merging on red since its just docs updates.

**Comment by asmirnov82** [comment]
Hi, @michaelgsharp 
I see, that 2 DataFrame related PRs actualy were not included into 3.0.1 release.
So, these lines should be removed from release-notes file:

- **Add support for Apache.Arrow.Types.TimestampType to DataFrame** ([#6871](https://github.com/dotnet/machinelearning/pull/6871))
- **Reorganize dataframe files** ([#6872](https://github.com/dotnet/machinelearning/pull/6872))

**Pull request merged**
