### PR TITLE
Support R4 label for binary trainers

### LINKED ISSUE #1874: Our binary learners estimators work only on top of boolean label
https://github.com/dotnet/machinelearning/blob/dfe9f3ad36cf382516276ad902a5f89a5f21c7e7/test/Microsoft.ML.Benchmarks/KMeansAndLogisticRegressionBench.cs
Fail currently because R4 is not supported.

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
fix #1874

### CODE REVIEW

**Comment by sfilipi** [comment]
>         public readonly SchemaShape.Column LabelColumn;

My problem with this is that we allow those types in the check, but the SchemaShape column contains only one ColumnType/RawType.... and that gets defined in the ctor of the trainers as a ...boolean.

---
Refers to: src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs:36 in ca674d3. [](commit_id = ca674d384cf6c3dcdfc5350a0e56e01a82ed2c0b, deletion_comment = False)

**Comment by sfilipi** [comment]
>                   TrainerUtils.MakeBoolScalarLabel(args.LabelColumn))

Like here, this defines it as a bool.. 

---
Refers to: src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs:184 in ca674d3. [](commit_id = ca674d384cf6c3dcdfc5350a0e56e01a82ed2c0b, deletion_comment = False)

**Comment by Ivanidzo4ka** [comment]
>                   TrainerUtils.MakeBoolScalarLabel(args.LabelColumn))

I don't like this either, but I can't come up with better solution. 
Array of supported columns a bit weird.
Don't pass anything for binary classification, is also lame.

---
In reply to: [447171216](https://github.com/dotnet/machinelearning/pull/1875#issuecomment-447171216) [](ancestors = 447171216)

---
Refers to: src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs:184 in ca674d3. [](commit_id = ca674d384cf6c3dcdfc5350a0e56e01a82ed2c0b, deletion_comment = False)

**Comment by sfilipi** [comment]
> > ```
> >               TrainerUtils.MakeBoolScalarLabel(args.LabelColumn))
> > ```
> 
> I don't like this either, but I can't come up with better solution.
> Array of supported columns a bit weird.
> Don't pass anything for binary classification, is also lame.
> 
> In reply to: [447171216](https://github.com/dotnet/machinelearning/pull/1875#issuecomment-447171216) [](ancestors = 447171216)
> 
> Refers to: src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs:184 in [ca674d3](https://github.com/dotnet/machinelearning/commit/ca674d384cf6c3dcdfc5350a0e56e01a82ed2c0b). [](commit_id = [ca674d3](https://github.com/dotnet/machinelearning/commit/ca674d384cf6c3dcdfc5350a0e56e01a82ed2c0b), deletion_comment = False)

Why not support just boolean? The users can always convert it.

**Comment by Anipik** [comment]
will it also enable R4 support for multiclass classfication ?

**Comment by TomFinley** [comment]
> Why not support just boolean? The users can always convert it.

This is the correct policy. Indeed have we codified this in the case of [`IDataView` implementation specifically](https://github.com/dotnet/machinelearning/blob/master/docs/code/IDataViewImplementation.md#getters-must-fail-for-invalid-types), but it also applies here.

`IDataView`s are composable structures. Also we are writing an API, and an API with too many "smarts" baked in never winds up being such a smart API.

Consider closing this PR. Thanks.

**Pull request closed without merging**
